### ISSUE TITLE
RFC: @marigold/config

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#100]
The dependencies in our root `package.json` grow very fast and it not easy anymore which dependencies are doing what and where they belong to.

To counteract this we could move configurations to a dedicated package (something like [this](https://github.com/sebald/unscripted/tree/master/config)). This would not remove any dot files in the root directory, but it would bundle dependencies with their corresponding tool. (e.g. all the webpack loaders that are required by storybook).

**Comment by viktoria-schwarz** [comment]
I agree with the idea but I don't really know how to sort the dependencies? Would we create a package each for storybook, jest, eslint and tsconfig?

**Comment by sebald** [comment]
Hmm. I make an easy one and you can do some more complex ones 🦹‍♂️

The basic idea is to have something similar to `themes`:

```diff
packages/
themes/
+ config/
+    tsconfig
+    eslint-config
+    prettier-config
+    ...
```
