### ISSUE TITLE
docs: create switch theme functionality to show components in their theme

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1034]
## Description

We need a functionality to show all components with all themes. That means that you can switch between our existing theme eg b2b, unicorn, ...

## Context

Better User Experience at using Marigold Docs. Users could switch between all themes. Makes easier usage for them.

## Use Cases 

I (developer) need a component from marigold. I can show the comp in my theme and not in an other theme.

## Consequences

Better user experience for all users of marigold.

**Comment by viktoria-schwarz** [comment]
Does it mean that for each page of the documentation site we can set a default theme and have the option on the site to switch to any other theme?

**Comment by ti10le** [comment]
It would be the best I think. Then we have as default our Marigold docs theme and you can show all parts of Marigold (which depends on a theme) in the theme you need. 
What do you mean @sebald ?

**Comment by sebald** [comment]
I would not use the docs theme for the component examples. Rather use the B2B or b2c (when there is one) as default and make a global switcher.

**Comment by ti10le** [comment]
I did not mean it that way. I would not take the docs theme for the components, too.
