### ISSUE TITLE
Refactor Heading component

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#1036]
## Description

<Heading> takes two props, as and variant. If you want to use the Heading as one different to h2, you need to set both props to the desired h. Though you can create a (default) h2 element styled with h1 variant styles.

## Context

Make the usage of the heading component as easy and intuitive as possible!

## Use Cases 

in case you want to display a h1, you need to set at least the variant, but in order to have the correct HTML element you need as="h1" AND variant="h1".

```tsx
<Heading as="h1" variant="h2">Example</Heading> // works now
<Heading variant="h1">Example</Heading> // styled as h1 but HTML element is still h2
<Heading as="h1">Example</Heading> // styled as h2 (default) but HTML element is h1
```

## Consequences

Have only one prop taking the desired heading style and not two, and also have the respective HTML element according to the styles (h1, h2, h3, h4, h5 or h6).

**Comment by sebald** [comment]
Not sure if this is a good idea. If the hardwire that we are mixing semantics with visuals.

The user doesn't care what HTML element is used, bit the bots are. Vice versa, bots don't care about the visual, but users are.
