### ISSUE TITLE
Should we move from CircleCI to Github Actions?

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#109]
- CI is closer to the repo and code?
- easier? better docs?
- Just pick everything from this list: https://github.com/sdras/awesome-actions

**Comment by viktoria-schwarz** [comment]
Why? Do we need any additional features we don't have yet?

**Comment by sebald** [comment]
Like I said in the first comment: Everything in one place and better docs.

**Comment by ti10le** [comment]
I wouldn't also move now. It looks nice but I think its more important to move forward with marigold. Maybe later :)

**Comment by sebald** [comment]
I am reopening this because I have some more evidence that we should start using Github actions:

**MORE AUTOTMATION!!!**

These look awesome:

- https://github.com/actions/labeler
- https://github.com/actions/stale

**Comment by viktoria-schwarz** [comment]
As the labeler automatically adds labels based on the changed files within a PR, we should talk about the labels we want to apply. I suggest to use
- **infrastructure** for all changes within packages/system, packages/types, config, and on the repo root
- **documentation** for all changes within markdown files no matter where they are
- **dependencies** for all changes within package.json files no matter where they are

Maybe/what do you think about the following:
- a **theme** label for changes within the themes folder
- anything more ?

**Comment by sebald** [comment]
Hm, I would

- tag everything in `packages` and `themes` with **enhancement**, because these are the "public" packages
- tag everything in `config` with **infrastructure**
