### ISSUE TITLE
Have a starting page in docs

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#1096]
## Description

On "/" there is no file so far (i.e. on entering the documentation site), and in order to see `start.mdx` you need to redirect to `/start`. It would be nice to have a proper index page.

## Context

404 page when you enter the docs page

## Consequences

Create index page or redirect to start.mdx, no matter what but we have a proper landing page!

**Comment by sebald** [comment]
We can also add a `index.tsx` inside `src/pages` depends on what we want on the front page.

**Comment by sebald** [comment]
Context: I tried to use a `index.mdx` but this led to some weird behavior and I didn't follow up on it. But we could investigate that and "fix" it.

**Comment by viktoria-schwarz** [comment]
For me creating a `index.mdx` in src/pages is completely fine, what "weird behavior" do you mean?

The front page should just display some first overview-like words, and not the 404 page :smile:

**Comment by sebald** [comment]
Try it you'll see 🙈

It basically can not handle empty routes. 

If we want something simple on the index page and not a lot of content, let's just put it in `pages`?

**Comment by viktoria-schwarz** [comment]
What I said is that an `index.mdx` in `src/pages` doesn't cause me any problems, I tried again and it's still fine :thinking:

**Comment by sebald** [comment]
Yes. I meant in /contents ... But also, Gatsby shouldn't read mdx from src/**/* only tax filers. I guess there is no way to disable it 😑
