### ISSUE TITLE
Theme with current core styles

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1105]
## Description

In order for the design system to be usable in our current products we need to mimic their look. Thus we need to create a `theme-core`.

## Context

Our current `theme-b2b` only reflects new products but not existing ones. But in order to get people on board we need to support the software they currently build.

## Consequences

Marigold can be used within our backend software.

**Comment by ti10le** [comment]
Heres a [confluence ticket](https://jira.rsvx.it/browse/CAT-2187) which is the result of a discussion between Laura, Toshi & Indre.
These are conventions and agreements reached which the core intends to implement step by step.

**Comment by ti10le** [comment]
Had meetings with Laura (UX) and Indre (Core Frontend): I will try to make the core-theme with the content of the linked Jira Ticket and the core Styleguide. If I had something prepared to show, I can talk with Indre and Laura about the changes and about the next steps.

**Comment by ti10le** [comment]
Waiting for Meeting which will be planned by Laura (UX/UI)

**Comment by ti10le** [comment]
See updates on our Confluence Projects page.
Buttons have an design update now: https://www.figma.com/file/4DRiB2S97m0PFcF6Y7zKGu/CR---UI?node-id=1975%3A1896

**Comment by ti10le** [comment]
If we got new input from core Ux/Ui designers we open a separate issue to make the incoming changes. This issue was mainly for creating the initial coe-theme.
