### ISSUE TITLE
Unify Gatsby wrappers

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1112]
## Description

Currently Gatsby's wrapper functions (`wrapRootElement` and `wrapPageElement`) are present in both configs, the SSR and browser. This is unnecessary since they both do the same.

## Consequences

Unified experience between browser and SSR. Better maintainability.

**Comment by ti10le** [comment]
`Note: The APIs wrapPageElement and wrapRootElement exist in both the browser and Server-Side Rendering (SSR) APIs. You generally should implement the same components in both gatsby-ssr.js and gatsby-browser.js so that pages generated through SSR are the same after being hydrated in the browser.`

@sebald this is from gatsby website. You think/know its possible/better to unify this?

**Comment by sebald** [comment]
This is basically what the quote says:

> You generally should implement the same components in both gatsby-ssr.js and gatsby-browser.js so that pages generated through SSR are the same after being hydrated in the browser.

**Comment by sebald** [comment]
And it's also what plugins, like `mdx`, do: https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-plugin-mdx/wrap-root-element.js

**Comment by sebald** [comment]
Ah! I don't mean unify the two wraps. They do something different, which BTW is also not clean in our repository, since not all providers are in `wraosRootElement`.

But rather unify the usage of those two wrappers, see the linked example.
