### ISSUE TITLE
Demistify GH Actions

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1115]
## Description

Currently we have the following actions.

- Coverage / Coverage (pull_request)
- Coverage / Coverage (push)
- Validate / Lint, typecheck & test (push)

In every actions the test suit runs and coverage reports are created. This is unnecessary overhead. Plus, The "Validate" actions includes three different types of checks. They should be separated so that we have an easier time identifying what's working and what not.

We have to clean up the tasks and have one action for each type of check: 

- Is the software working? → test+coverage+coverall
- Does the code adhere to our formatting rules? → lint+prettier
- Are there any type issues? → typecheck

## Context

The actions will run longer and longer with the progression of the project. Uncool!

## Consequences

Hopefully we'll have clearer and more informative GH Actions and they finish faster.

**Comment by viktoria-schwarz** [comment]
The new actions could look like this:

- Typecheck --> `yarn typecheck` [on push]
- Format --> `yarn lint` and `yarn format` [on push]
- Test --> `yarn test` and `yarn coverage` [on PR and push]

Also, we can use cache for the yarn deps to save time.

**Comment by sebald** [comment]
Yarn format doesn't check, but actually runs prettier. Sorry this even work? 😳

Yarn coverage also runs the tests if I am not mistaken.
