### ISSUE TITLE
Add Image component to marigold docs

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1116]
## Description

We need our own Image component like all other components in marigold docs.
To reach this we have to show our image component in action. This means you can show an image with marigold image component in gatsby.

## Context

Our target is to have all components from marigold storybook in gatsby docs.

## Consequences

we have a complete palette of our components on marigold docs page

**Comment by viktoria-schwarz** [comment]
If we directly try to use the `<Image />` component Gatsby doesn't render the image; therefore we need `gatsby-image`.

**Comment by viktoria-schwarz** [comment]
Works as in https://github.com/marigold-ui/marigold/blob/main/docs/src/components/Logo/Logo.tsx
