### ISSUE TITLE
docs: code between single quotes are not displayed

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1124]
## Description

Marigold docs: everything whats in single quotes are not displayes in the gatsby docs page.

## How to reproduce

1. Go to a file which uses single quotes to show inlineCode
2. See error

## Expected behavior

Should be displayed as highlighted code

## Screenshots

![image](https://user-images.githubusercontent.com/59875255/122740979-cce4e100-d284-11eb-92b5-1b2b4c37a690.png)

**Comment by sebald** [comment]
`{children is missing in the component}`
