### ISSUE TITLE
How to help build layouts?

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#118]
There are three ways I can think of all follow the principle that components are not providing surrounding white space (a.k.a margin/padding).

### 1. `<Space>` component

There is exactly one component that can add white space. There is no abstraction for spacing, just use margin/padding. It has to be inserted everywhere where space is required.

```jsx
<Box>
	<Space mt={["medium", "large"]}/>
	<Box></Box>
	<Space my={["medium", "large"]}/>
	<Box></Box>
	<Space my={["medium", "large"]}/>
	<Box></Box>
	<Space mb={["medium", "large"]}/>
</Box>
```

### 2. "Space Props"

Every component of the design system exposes spacing props. They have to be applied on component instance basis.

```jsx
<Box>
	<Box my={["medium", "large"]}></Box>
	<Box mb={["medium", "large"]}></Box>
	<Box mb={["medium", "large"]}></Box>
</Box>
```

# 3. Using dedicated layout components

This is what [Braid](https://seek-oss.github.io/braid-design-system/foundations/layout) does. You can find more info about the reasoning in [this talk](https://youtu.be/jnV1u67_yVg?t=583).

The gist is that they have dedicated components for the different layouts (e.g. horizontal, vertical, grid, ...). This results in extra HTML elements, but is less verbose in my opinion.

```jsx
<Stack space={["medium", "large"]}>
	<Box></Box>
	<Box></Box>
	<Box></Box>
</Stack>
```

**Comment by ti10le** [comment]
I dont know which is the best way but with my experience and feeling i would say way 2 or 3. Way 1 seems to me elaborate.

**Comment by sebald** [comment]
@ti10le No that wouldn't work 😃

I think I would go with 3, because I think it's the best API.

**Comment by viktoria-schwarz** [comment]
I agree using the 3rd option as it causes the least redundancy :thinking:

**Comment by sebald** [comment]
Decided to go with layout components.
