### ISSUE TITLE
OverlayProvider ist added multiple times with the MarigoldProvider

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1195]
## Description

The `<MarigoldProvider>` always adds react-aria's OverlayProvider. Especially if you using cascading theming. There should only be a single instance of the provider at any time.

Otherwise this can lead to inaccessible overlays.

**Comment by viktoria-schwarz** [comment]
Could [this](https://github.com/facebook/react/issues/14520#issuecomment-451077601) be a solution to the problem (in useTheme.tsx) since we are stacking the providers there?

**Comment by sebald** [comment]
Not quite, the lib solved a problem before hooks existed (requiring multiple context consumers). This is why it is deprecated now.

The solution is actually much simpler and stupid 😄

**Comment by ti10le** [comment]
@sebald Should I just try to check if the provider is there before adding it?

**Comment by sebald** [comment]
> @sebald Should I just try to check if the provider is there before adding it?

@ti10le that's one solution, but how do you check that? 🙂

**Comment by ti10le** [comment]
If it is possible at all I have to find out first 😀

**Comment by ti10le** [comment]
How do you see that OverlayProvider added multiple times?
I can only see this in devTools. Looks like theres only one time:
![image](https://user-images.githubusercontent.com/59875255/130580860-14220632-5800-4187-9cb4-a85394983ba8.png)

**Comment by sebald** [comment]
See description -> cascading

**Comment by ti10le** [comment]
Ok now I get it.
@sebald we have just asked ourselves the question whether we now only use the MarigoldProvider or also the ThemeProvider if we want to cascade e.g. only the theme?

**Comment by sebald** [comment]
My gut says `<MarigoldProvider>` since most users will only use the components package, hopefully. And they works be confused what the difference between the two is (since it's an Implementation detail).

Also: what if you don't know if the "outer" stuff uses marigold!?

**Comment by ti10le** [comment]
waiting for #1317
