### ISSUE TITLE
Add Root styles

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1197]
## Description

We currently don't have an option to add root styles (e.g. html, body). This is convenient for building layouts to set background and spacing for apps.

## Context

If you want to emulate this with the current state you have to wrap your app in an addition `div`. This shouldn't be necessary :-/

## Use Cases 

- Set `body` background color
- Set `body` margin/padding
- Set global font family

## Consequences

Option to "globally" set CSS.

**Comment by viktoria-schwarz** [comment]
Where do you imagine these root styles to be? Should they be set once for all applications or somehow flexible and manageable each time you use a component?

**Comment by sebald** [comment]
So here is the question: do the rest styles solve the mentioned use cases?

I imagine there global or root styles be set via the theme. So that we (for example) can set the font once in our docs or give the whole page a background color.

**Comment by viktoria-schwarz** [comment]
Ahhh, you mean setting these values within the theme. Okay that makes sense :+1:

**Comment by viktoria-schwarz** [comment]
So to make that work we could add a Component `<RootStyles />` with some rootStyles (given in the theme) and place it next to the children in the Provider?

**Comment by sebald** [comment]
Exactly

**Comment by sebald** [comment]
BTW hast checked theme-ui. They got a reference for you ☺️

https://github.com/system-ui/theme-ui/blob/develop/packages/theme-provider/src/index.tsx

In the file there is also a solution for the overlay issue (since root styles should only be applied once too).

**Comment by viktoria-schwarz** [comment]
Yes, I've seen how they do it, but they use their jsx to create the styles, that's what I meant that I don't know how to inject the root object from the theme.

**Comment by sebald** [comment]
> Yes, I've seen how they do it, but they use their jsx to create the styles, that's what I meant that I don't know how to inject the root object from the theme.

@viktoria-schwarz trick question: is that different from what we do? And if so, how? 

Also, how far are you in the react course 😬

**Comment by viktoria-schwarz** [comment]
Not as far as I would like to be :)

And no it's not different, I could make it work (I think yesterday when I tried it I just used wrong imports), though now my tests still fail. I'm trying to make it work!

**Comment by viktoria-schwarz** [comment]
closing via #1230

**Comment by ti10le** [comment]
PR was reverted. Issue still in work.

**Comment by sebald** [comment]
> PR was reverted. Issue still in work.

Is there a commit to reproduce the issue? And what's not working correctly?

**Comment by ti10le** [comment]
waiting for #1317
