### ISSUE TITLE
Storybook "Show Code" shows [object object] for some components

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#1226]
## Description

When you click on Show Code in storybook, the code with the components used should be displayed. Instead, it sometimes displays the following:

```
<[Object object]>...
```

## Expected behavior

There should be `<Text>...` no matter which component is used 

It happens with the `<Text>` component and in each place it is used (e.g. inside `<Alert>`)

**Comment by ti10le** [comment]
closed by #1641 
We have no longer docs in our storybook
