### ISSUE TITLE
Design & Component update - Menu + MenuItem

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1233]
## Description

Update our menu & menuItem component that they are fully functional. Now menu is just a button which renders a hidden div. It's not useful in production.
Implement react-arias useMenu functionality and style it like in the design.
Maybe we need the Item from react-aria like in the select component instead of an own menuItem.

[reac-aria useMenu](https://react-spectrum.adobe.com/react-aria/useMenu.html)
[Figma Design](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/🏵️Marigold?node-id=1571%3A0)

## Context

Have a full functional menu component wich passes react-aria rules.

## Use case

First usage in marigold side navigation.

## Consequences

Menu component is ready to be used in production. Improvement for the component itself and the marigold docs page.

**Comment by sebald** [comment]
Closed via #2018
