### ISSUE TITLE
Import Item in select storybook crashes

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#1255]
## Description

In Select.stories.mdx, the `<Item>` component isn't imported and displayed;

## How to reproduce

Desired usage of the Select component would be as follows (in storybook):

```
<Select>
	<Item>1</Item>
	<Item>2</Item>
</Select>
```

But storybook crashes and logs spit out `Unknown element <[object Object]> in collection`.

Wrong import because `<Item>` is from an external library??

**Comment by ti10le** [comment]
will be closed by #1660 
No docs no problems :) 
It works in our new story way 🎉
