### ISSUE TITLE
Should we write tests for themes?

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#129]
I am not sure wether we should write tests for themes. The base theme already has specifications for writing a theme. Maybe its useless to test an object. Coverage always shows that the themes are not tested. I think we have three options:

- we let it be as it is
- exclude theme files from coverage check
- write tests for the themes

**Comment by ti10le** [comment]
@sebald @viktoria-schwarz what do you mean?
I think option two is the best if its possible.

**Comment by viktoria-schwarz** [comment]
If we use a good naming convention like xx-theme.ts we can just exclude these files, I agree :slightly_smiling_face:

**Comment by sebald** [comment]
It's more simple than that! We can just exclude the `themes` folder!
