### ISSUE TITLE
bug: css class order changes at using useTheme in MarigoldProvider

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1317]
## Description

The css class order changes if you are using useTheme() hook in MarigoldProvider. (this was recognized at #1197)

## How to reproduce

1. use useTheme in MarigoldProvider (like with the GlobalStyles in the linked issue)
2. make gatsby build
3. gatsby serve
4. See that the style order is not the same as local devmode or in current live state.

## Expected behavior

Css classes should be the same order in local dev mode, local production (gatsby serve) and live.

## Screenshots

![image](https://user-images.githubusercontent.com/59875255/133443640-5baed70f-7dce-4e85-aa37-363fefb258c2.png)
![Bildschirmfoto 2021-09-15 um 09 54 05](https://user-images.githubusercontent.com/59875255/133443646-65b5d4c9-9082-4ba5-a565-362faeca7611.png)

**Comment by ti10le** [comment]
The variant and custom styles are overridden by reset.base styles (css class css-ase7ea). The order is changed (current guess) by using the useTheme hook in the MarigoldProvider.

**Comment by ti10le** [comment]
'@emotion/react' and '@emotion/css' are not good at working together. We found out that this combination changes the order of the css styles. One solution is to remove the css() function from emotion/css which is used in reset.ts
After we removed that and changed the useStyles hook a little bit we got a production build which are the same as in dev mode.

**Comment by ti10le** [comment]
Still trying to find a solution for this. The current problem is that the GlobalStyles cannot be replaced by changing the theme. You should set GlobalStyles which are replaced by another theme globals (not added)

**Comment by ti10le** [comment]
We found out that the best way is to deepmerge alle styles inside useStyles or inside useClassname.

**Comment by viktoria-schwarz** [comment]
I would definitely go for option 3, a.k.a. putting everything in the correct order with a deepmerge in useStyles.
In my understanding we need to merge the `reset.base` (base styles) with the reset styles of the given  `element` and this outputs the `resetClassName`. Same with `base` and `customClassName` that outputs the new `customClassName`.

**Comment by ti10le** [comment]
I would also go for this option.
What are your thoughts @sebald ?

**Comment by sebald** [comment]
@viktoria-schwarz @ti10le that option doesn't use a deep merge, if you referring to this doc: https://github.com/marigold-ui/marigold/blob/global-css-with-separate-caches/packages/system/src/issues.md

The deepmerge is causing the problem. It solves the ordering issue and creates an issue with overriding props. See example.

**Comment by sebald** [comment]
moved everthing here: https://github.com/marigold-ui/marigold/discussions/1372
