### ISSUE TITLE
Make error prop boolean and add errorMessage in all components using error

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1373]
## Description

We have a few components which are using an error prop as string. We check in the components if theres no empty string and then show the error.

- Radio already done in #1336
- Checkbox already done in #1337
- Field
- Select

## Context

Its not nice and safe to use the error as string. Users would also think you have to add error prop as boolean.

## Consequences

Better understood props in all components. Easier and more intuitive usage of the error prop.

**Comment by sebald** [comment]
Which one? Can the button be in the same state at the same time?
