### ISSUE TITLE
Improve docs CodeBlock actions to display demo components

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1379]
## Description

We need a possibility to display our components as a demo like in the current [marigold prototype](https://www.figma.com/proto/TIRxkIDpdqb52J52PldLxl/Guidelines?page-id=0%3A1&node-id=12%3A847&viewport=241%2C48%2C0.12&scaling=min-zoom&starting-point-node-id=12%3A847&show-proto-sidebar=1)
[Demo Design with styles](https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=12%3A847)
We have to extend the current ActionTypes in CodeBlock.tsx. ```tsx ...

There should be one option to display them:
- one component alone or next to each other like in the button example
- without any bordered box around them
- without showCode button
- without copy button

## Context

With this implementation we can step further to our current main target: **improve the marigold docs page**

## Use Cases

You have to start with a 'demo' at creating a components page in marigold docs. You can implement this with this new improvement.

## Consequences

We have a reusable implementation to display the marigold components

**Comment by ti10le** [comment]
Yes he knows about all but only if you use one of the ActionTypes. Maybe you thinking of the "Preview" type? I am thinking about an option where you display only the component like in the prototype and like I described above.

**Comment by sebald** [comment]
We pass the components to `react-live` . Why does the type make a difference? 

I can quite follow the description because in the figma design are multiple examples 🙈

**Comment by ti10le** [comment]
The type makes the difference at how to show the components? And we can't show them right now with CodeBlock.tsx and without the points in the issue description. I refer to how to implement exactly that from the prototype.
![image](https://user-images.githubusercontent.com/59875255/136742075-e350f697-b302-4767-95ad-5f2c4f006085.png)
![image](https://user-images.githubusercontent.com/59875255/136742108-3fbb8824-ea0f-4d61-b35b-f8c14ded8f86.png)
![image](https://user-images.githubusercontent.com/59875255/136742129-05c07eda-bff5-4082-bafe-a3c8cbeee74c.png)
![image](https://user-images.githubusercontent.com/59875255/136742149-e90d80d9-fe77-45d9-a8af-859a8e8b9596.png)
