### ISSUE TITLE
Improve docs CodeBlock to display ShowCode and Copy button as icons

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1381]
## Description

We need a possibility to display our components with decent small showCode and copyCode icons under the component preview. See here: [marigold prototype](https://www.figma.com/proto/TIRxkIDpdqb52J52PldLxl/Guidelines?page-id=0%3A1&node-id=12%3A847&viewport=241%2C48%2C0.12&scaling=min-zoom&starting-point-node-id=12%3A847&show-proto-sidebar=1)
[Design with styles](https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=118%3A1289)
We have to extend/change the current ActionTypes in CodeBlock.tsx with an option to handle this.
We have to decide in which way the code should be shown under the displayed components.

## Context

With this implementation we can step further to our current main target: improve the marigold docs page

## Use Cases

We implement the current marigold prototype and use this new feature to display components

## Consequences

We can create and improve our component pages like in the prototype

**Comment by sebald** [comment]
Not quite sure what you want to do here 😐

**Comment by ti10le** [comment]
![image](https://user-images.githubusercontent.com/59875255/136738596-1a2585f2-dfd4-4c29-80d9-fa518e568b74.png)

**Comment by sebald** [comment]
Don't get why we blindly should implement this. How does this work with other components?

**Comment by sebald** [comment]
I meant how does this look for other components. I am not talking about the implementation.

**Comment by sebald** [comment]
> Yes but I was confused because this has nothing to do with variants.

This was a comment at the whole page. We can not show certain variants because themes nicht not have them
