### ISSUE TITLE
Document Design Principles

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#144]
**By "design principles" I mean on a technological level, not design design.**

--- 

When we really start to do some documentation, I guess we also need to tell people about the philosophy and our thinking behind the components and their API. For example, why did we chose the "Box-principle" or why do we use layout components (#118)?

This issue should be used to collect these things. I'll update the description based on our discussion below.

---

## Structure

Let's plan a structure of the docs first:

**INTRODUCTION**

- [x] Getting Started (#1744)
- [x] About (#1761)
- [ ] Design Principles
  - strict vs flexible API
  - style props + variants + theming
  - composition
  - a11y
- FAQ
  - [x] What are Design Systems (#1752) 
  - [ ] Why is component `X` missing?
  - [ ] Why React?
  - [ ] Why emotion (or CSS-in-JS)?

**CONCEPTS**

- [ ] Primitives
  - Box
- [ ] Styling
  - Design Tokens
  - CSS-in-JS
  - Responsive Values
- [x] Layout
  - isolated layouts (margin considered harmful)
- [ ] Theming

**Comment by ti10le** [comment]
We will do this when we have the Marigold docs gatsby page.
Maybe we get content from UX/UI team

**Comment by viktoria-schwarz** [comment]
For the record: https://visly.app/blogposts/layout-isolated-components

**Comment by ti10le** [comment]
Todos:
- [ ] Why CSS-in-JS?
- [X] The Box as a primitive
- [ ] Design Tokens + Scales / 8pt Grid (maybe infos from [Confluence Marigold Layout](https://confluence.rsvx.it/display/DESIGN/Layout)
- [ ] Responsive Style Values (@theme-ui/css)
- [X] Theming (design token interpolation + variants)
- [ ] Layout components (margin considered harmful)

**Comment by ti10le** [comment]
> * Design Tokens + Scales / 8pt Grid (maybe infos from [Confluence Marigold Layout](https://confluence.rsvx.it/display/DESIGN/Layout))

Should we use the same doc like in confluence? With all links an images? 
@sebald @viktoria-schwarz @andres-dediego
I would say yes.
Have made a branch to start with this guide: origin/guide-design-tokens

**Comment by viktoria-schwarz** [comment]
I don't think we have implemented all the functions yet, nor the 8 pt grid or am I wrong?

**Comment by sebald** [comment]
That's not a component but rather a design principle :)

Viktoria Schwarz ***@***.***> schrieb am Mi., 6. Okt. 2021,
15:37:

**Comment by sebald** [comment]
No

**Comment by sebald** [comment]
## Introduction

Principles 

- strict vs flexible
- composition (of components)
- a11y

## Concepts

- Primitive: Box
- Styling: Design Tokens, CSS-in-JS, Responsive Values
- Layout: isolated layouts (margin considered harmful)
- Theming: variants + size, styling components
- Forms: how to use form components, validation?

## Recipes

- Navigation
- Apps hell
