### ISSUE TITLE
Fix deploy_storybook task in circleci

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#147]
The pipeline failes because of taking more than 10 minutes to deploy_storybook.
"Too long with no output (exceeded 10m0s): context deadline exceeded"

I think we have two options:
- we need to either increase the output timeout
- add some dummy output so that the task is not killed

**Comment by sebald** [comment]
Or move to github actions! :D

**Comment by viktoria-schwarz** [comment]
Just implemented storybook deployment like in https://github.com/storybookjs/storybook-deployer#deploying-storybook-as-part-of-a-ci-service
But I agree to go for GitHub Action :)

**Comment by viktoria-schwarz** [comment]
But I want to try to fix it before we move to GH Actions
