### ISSUE TITLE
Search and copy Marigold Icons as <svg> in documentation

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1520]
## Description

We want have a possibility to copy the marigold icons as svg directly on the docs page. Integration on our existing icons page.
https://www.figma.com/proto/TIRxkIDpdqb52J52PldLxl/Guidelines?page-id=701%3A8113&node-id=710%3A11078&viewport=247%2C48%2C1.2&scaling=min-zoom&starting-point-node-id=701%3A8330
https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=701%3A8113

## Context

Some teams that do not use react need a way to extract icons as <svg> element from the documentation.

## Use Cases

Core member copy icons from marigold and insert the svg in their code.

## Consequences

More people are using marigold and take something from our documentation. Higher number of visitors and users.

**Comment by sebald** [comment]
Closed via #1564 

@ti10le would like to close this since it's done. Everything else is just the 🍒 on top

**Comment by ti10le** [comment]
@sebald okkeeee
