### ISSUE TITLE
Switch themes in storybook

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#154]
![https://raw.githubusercontent.com/tonai/storybook-addon-themes/HEAD/media/demo.gif](https://raw.githubusercontent.com/tonai/storybook-addon-themes/HEAD/media/demo.gif)

We want to have the option to easily switch themes within storybook. This can be done via addon. There is already one called `storybook-addon-themes` can we use this? If not do we have to write our own :(

https://www.npmjs.com/package/storybook-addon-themes

**Comment by ti10le** [comment]
If it's possible with this addon, we need a custom decorator like: https://www.npmjs.com/package/storybook-addon-themes#custom-decorator

**Comment by ti10le** [comment]
@sebald @viktoria-schwarz ? I think we dont need this right now.
