### ISSUE TITLE
<Select> has hardcoded variants for <Button> and <Label>

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1571]
## Description

The `<Select>` component has some hard coded variants that we need to look at. This usually should be solved via __baseCSS or conditional function. Variant's purpose is to allow users to add extra markup to components. In the `<Select>` component every theme would be required to have a variant for:

- label.disabled
- label.above
- 'button.select.errorOpened'
- 'button.select.error'
-  'button.select.open'
- 'button.select'

## Context

We don't want to force the Theme to have specific variants in a component.

## Consequences

Easier to write and access a theme. Easier to use the Select component.

**Comment by ti10le** [comment]
Fix also the green outline from listbox if select is opened

**Comment by sebald** [comment]
@ti10le close?

**Comment by ti10le** [comment]
Nooo only hard coded label is removed. Select has more hard coded variants. I am still working on this

**Comment by sebald** [comment]
Closed via #2048
