### ISSUE TITLE
Storybook: Theme ignored in Canvas tab

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#161]
The Box works in the "canvas" tab, but weird things happen in the "docs" tab. I don't know where the color comes from, there is no provider or theme applied.

## Canvas

`color: orange` (yes the CSS value "orange")!

![image](https://user-images.githubusercontent.com/985701/77846254-0e3b2d80-71b5-11ea-8b06-56ecfa270947.png)

## Docs

`color: #FC521F` (from ???)

![Screen Shot 2020-03-27 at 11 13 50](https://user-images.githubusercontent.com/985701/77846259-15fad200-71b5-11ea-94d8-8242ebfb5ba3.png)

**Comment by ti10le** [comment]
@sebald you still have this bug? It's working for me.

**Comment by sebald** [comment]
Did not check it, honestly. Will do later.

Did I did this on accident? 😅

**Comment by ti10le** [comment]
That was my thought 😀

**Comment by sebald** [comment]
yup, I am on 279bc1b

**Comment by sebald** [comment]
Checked the code again. Actually, `canvas` is correct. I have no clue where the `#FC521F` comes from that is used in the docs 😥

**Comment by ti10le** [comment]
I'm still having `color: orange;` in both tabs. Canvas and Docs are the same.
@sebald can we close this or you want check it again? 😄

**Comment by sebald** [comment]
Guess @viktoria-schwarz is the tire breaker 😐 if it's only me close it.

**Comment by viktoria-schwarz** [comment]
It's working for me as well, all colors as expected!
