### ISSUE TITLE
Use new <Profiler> component to Profile <Box>?

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#162]
The `<Box>` component will be used a loooooooot. We should make sure it doens't becomes the bottleneck.

Can we use the <Profiler>? More info: https://reactjs.org/docs/profiler.html

**Comment by viktoria-schwarz** [comment]
Ist das so gedacht dass man <Profiler> um die Box-Komponente wrappt oder dass man das macht wenn man z.B. im Button die Box verwendet? Also dann 
`<Profiler id="button onRender={onRenderCallback}><Box as="button"... /></Profiler>`
Und die onRenderCallback Funktion loggt einfach nur die Zeiten usw.
