### ISSUE TITLE
Component update - Select - refactoring and b2b design update

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#1648]
## Description

Correctction to the select component: 
The hight size is 40px instead of 32px.  The focus color and the selection color changed to orange for the B2B Theme.
Figma Link: https://figma.fun/443YqC

## Context

Fixing the color Palete to the Theme, as well to making the dropdowns mobile friendly and having the same dimensions.

## Consequences

It will be easier to select and read, as well it will be an homogeneous theme.

**Comment by ti10le** [comment]
@all-contributors please add @andres-dediego2  for design, doc

**Comment by sebald** [comment]
Closed via #2048
