### ISSUE TITLE
Component update - Select - add search functionality

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#1649]
## Description

Create a new component.  It is exactly like the normal select component, but aditionally you can search on the list when you click on it.

**Comment by ti10le** [comment]
think about this if you work on this issue: [react-aria useSearchField](https://react-spectrum.adobe.com/react-aria/useSearchField.html)

**Comment by ti10le** [comment]
Maybe use our Searchbar #1686

**Comment by ti10le** [comment]
@andres-dediego2 we need a design in figma and more clarification on how to implement the search.
