### ISSUE TITLE
Component - Multiselect

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#1650]
## Description

Dropdown with the option of selecting multiple items.
**https://figma.fun/20S0EX**
doku: https://www.figma.com/proto/TIRxkIDpdqb52J52PldLxl/Guidelines?page-id=0%3A1&node-id=868%3A9410&viewport=241%2C48%2C0.14&scaling=min-zoom&starting-point-node-id=12%3A847

It must include a Tag component that appears when selecting an item or more of the list.  When there is not more space to render more Tags on the dropdown, it should show a tag with the icon "icon-more", that looks like 3 points aligned horizontally (check the doku).nsequences

**Comment by ti10le** [comment]
If someone works on Multiselect think about react-aria functionality. There're a few examples for implementation:
- [Combobox](https://react-spectrum.adobe.com/react-aria/useComboBox.html)
- [Select](https://react-spectrum.adobe.com/react-aria/useSelect.html)

**Comment by ti10le** [comment]
@andres-dediego2 first figma link needs an update. First and second links design is not consistent. More clear description please.

**Comment by sebald** [comment]
Needs a different name? Since a multiselect is something like this: https://web.dev/building-a-multi-select-component/

**Comment by andres-dediego2** [comment]
@ti10le  ich habe es updated, lass uns darüber reden so schreibe ich besser den Beschreibung

**Comment by andres-dediego2** [comment]
@sebald wie soll ich am bestens nennen? 
In die Design Systems ich als Referenz habe, das Komponente heißt "Multiselect"

**Comment by sebald** [comment]
@andres-dediego2 welches DS ist das denn? In dem Design sind jetzt keine Tags mehr drin, kann das sein?

Ein multi select is ein `<select multiple>`.
Beispiel: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#advanced_select_with_multiple_features

**Comment by andres-dediego2** [comment]
Update: 
wie können es "select - combobox" nennen, passt? 
https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=2676%3A2443

Da ist auch die steps erklärt, falls fragen lass mich bitte wissen :)
