### ISSUE TITLE
Theme debug warning

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1684]
## Description

We should have a way to debug themes, especially if a value does not exist but `theme-ui` wants to interpolate it for us (e.g. a `variant`). This warning should only exist in development.

## Context

It is inconvenient to debug style related issues. Especially because most of the time it's was just a typo or you forgot to add something (like a variant).

## Consequences

It should be easier to debug theme when you forgot a `variant`. It's also nice for testing, because you immediately know that you didn't wrap the test in a `ThemeProvider`.

**Comment by sebald** [comment]
We could use `invariant` for this: https://www.npmjs.com/package/invariant

**Comment by ti10le** [comment]
maybe check provider with this: https://kentcdodds.com/blog/how-to-use-react-context-effectively

**Comment by sebald** [comment]
Using the hook made stuff way easier to debug, closing this for now.
