### ISSUE TITLE
Component - Accordion

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1687]
## Description

Accordion component to display some information by click on the main part of the accordion
- A11y from aria: [useAccordion](https://reactspectrum.blob.core.windows.net/reactspectrum/d77b35e970e5549f66b47a83f07423f5c93b7297/docs/react-aria/useAccordion.html)
- Figma Design: currently not existing
- [Braid DS Accordion](https://seek-oss.github.io/braid-design-system/components/Accordion)
- [Carbon DS Accordion](https://react.carbondesignsystem.com/?path=/story/components-accordion--accordion)
- [mui](https://mui.com/components/accordion/)

## Context

We need this component to make the Design System more complete and to support some use cases with n accordion.

## Use Cases

In the new Checkout to click on Checkbox/Radio/Arrow and display information.

## Consequences

Accordion can be used from marigold and does not have to be built by yourself.

**Comment by sebald** [comment]
`react-aria` support is only in alpha

**Comment by sebald** [comment]
Superseeded by #2388

**Comment by sarahgm** [comment]
some help: 
- https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/accordion/src/Accordion.tsx
- https://reactspectrum.blob.core.windows.net/reactspectrum/d77b35e970e5549f66b47a83f07423f5c93b7297/docs/react-aria/useAccordion.html
- https://kenneth-gray.github.io/react-aria-accordion/

**Comment by sarahgm** [comment]
@sebald not cool https://github.com/adobe/react-spectrum/issues/1989

**Comment by sarahgm** [comment]
disabledKeys

**Comment by sarahgm** [comment]
Notes:
- should our component also marked as `beta`?
- right now only `defaultExpandedKeys` are allowed
- no disable
- no special styles
- also warning which says `<Item> with non-plain text contents is unsupported by type to select for accessibility. Please add a `textValue` prop.`

something I don't thought of @sebald
