### ISSUE TITLE
Component - Carousel

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1688]
## Description

Carousel component to display some options to click and show image/thumbnail

- Figma Design: currently not existing
- [10 React carousel libs](https://openbase.com/categories/js/best-react-carousel-libraries)
- [bootstrap](https://react-bootstrap.github.io/components/carousel/)
- [a11y Carousel Concepts](https://www.w3.org/WAI/tutorials/carousels/)

## Context

We need this component to make the Design System more complete and to support some use cases with a carousel.

## Use Cases

In the new Checkout to choose between different ticket covers.

## Consequences

Carousel can be used from marigold and does not have to be implemented by yourself.

**Comment by sebald** [comment]
Do we want this in Marigold? Reason: the requirements for a carousel can be very different depending on the context.

**Comment by sebald** [comment]
https://gui-challenges.web.app/carousel/dist/
