### ISSUE TITLE
Component - Spinner or Loading

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1689]
## Description

- A11y from aria: [useProgressBar with example](https://reactspectrum.blob.core.windows.net/reactspectrum/d77b35e970e5549f66b47a83f07423f5c93b7297/docs/react-aria/useProgressBar.html)
- Figma Design: currently not existing
- [Braid DS](https://seek-oss.github.io/braid-design-system/components/Loader)
- [Carbon DS](https://react.carbondesignsystem.com/?path=/story/components-loading--default)
- [theme-ui](https://theme-ui.com/components/spinner)

## Context

We need this component to make the Design System more complete and to support some use cases with a loading state.

## Use Cases

In the new Checkout show loading state during waiting time e.g. by handling data.

## Consequences

Spinner can be used from marigold and does not have to be implemented by yourself.

**Comment by sebald** [comment]
https://uiball.com/loaders/

**Comment by michael-p** [comment]
Still relevant!
