### ISSUE TITLE
Document design concept and decisions

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1696]
## Description

We did a presentation about the design system, but didn't really talked a lot about our philosophy and concepts. We should write that down.

## Context

There is and will be a lot of questions why we chose a certain technology or API. This could help mitigate the question flood.

## Consequences

Consumers can better understand the underlying decision that were made.

## Questions to Answer

- How we design components and their API: strict vs flexible
- Why React?
- Why CSS-in-JS

**Comment by ti10le** [comment]
Is it not enough what we have on [CSS-in-JS](https://marigold-ui.io/foundation/css-in-js) ?

**Comment by ti10le** [comment]
Duplicate to #144 ?
I think we can close 144 to have a better overview. Maybe move something to this issue? E.g. an explanation on how to build Layout?
