### ISSUE TITLE
Component - Grid

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1716]
## Description

Create a Grid component to build every kind of Layout if Stack or Columns components are not enough.

## Context

Build complex Layouts with marigold. 

## Use Cases

Building Page Layout. Maybe first usage in marigold docs.

## Consequences

Marigold supports building complex layouts.

**Comment by sebald** [comment]
Should we change this to "more layout" components? 😄

**Comment by ti10le** [comment]
I think it's more clear to have an issue with a name of the component you have to build. I thought grid contains all the remaining layout components, right?

**Comment by sebald** [comment]
It's not about containing. Yes we want dedicated components for common layouts (Stack, Inline, Columns, ...)

A Grid could mean two things:

1. low level component that exposes the CSS grid API as props
2. a component that renders a certain grid (x and y axis) by default with sensible responsive defaults

Question is: do we need 1.?

**Comment by sebald** [comment]
Also: do we want to build all layouts with grids? Stack for example can be build with flexbox already.

**Comment by sebald** [comment]
My suggestion: build common layouts first and explore if we need the Grid abstraction.

**Comment by ti10le** [comment]
Ok 👍🏼
