### ISSUE TITLE
Building Forms with Marigold

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1721]
## Description

Forms make up a majority of apps, we already have most of the necessary form inputs but no strategy how to compose forms. We should explore a way how users should build forms with Marigold. Meaning,

- How to compose multiple form inputs into one larger form
- How to do validation and error signaling
- How to handle state over multiple elements (input, label, message)
- How to handle user interaction with forms
- (Preferred practices, like using `react-hook-form`)
- Link to [joshwcomeau.com/react/data-binding](https://www.joshwcomeau.com/react/data-binding/)

This should include documentation as well as some adjustments to the current components, if necessary.

## Context

Create guidelines and examples  how to build forms with Marigold.

## Consequences

Enable users to build forms in a consistent and maintainable way.

**Comment by ti10le** [comment]
Good [Article](https://dev.to/pmbanugo/looking-for-the-best-react-form-library-in-2021-it-s-probably-on-this-list-e2h) to find a react form tool

**Comment by ti10le** [comment]
[React Forms - Formik vs. Hook-Form vs. Final-Form](https://blog.appseed.us/react-forms-formik-vs-hookform-vs-finalform/?ck_subscriber_id=1689510808)

**Comment by sebald** [comment]
Example: Verwaltung > Kunde

**Comment by benediktgrether** [comment]
I don't know if it necessary to link this article Sebastian send it but here it can't be going lost. 

https://www.joshwcomeau.com/react/data-binding/
