### ISSUE TITLE
useToggle warns because of arria error

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1722]
## Description

Seems like we broke some aria rules 🙈

## How to reproduce

1. Run tests suite. 
2. Warning: `If you do not provide children, you must specify an aria-label for accessibility`

## Expected behavior

No warning 😄

**Comment by ti10le** [comment]
@sebald - This is why in the reac-aria example they are using children as label. We are using props.label and then we have no children and have to specifiy an aria-label.
Better to add aria-label to the input or change the component that it have children instead of label prop?

**Comment by ti10le** [comment]
I would do it with children:
`<Checkbox label='Foo' /> --> <Checkbox>Foo</Checkbox>`
