### ISSUE TITLE
Document `@marigold/system`

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1742]
## Description

Currently there is no documentation for your `system` package, expect `Box` and `SVG`.

## Context

We need to have documentation about the "inner workings" too, especially because `useTheme` and `useResponsiveValues` are hooks from this package.

**Comment by sebald** [comment]
@sarahgm want to try this next? :)

**Comment by sarahgm** [comment]
@sebald  sure can we talk about this before?

**Comment by sarahgm** [comment]
maybe hooks page too
