### ISSUE TITLE
Docs: Code blocks should have default behavior and opt into <Preview>

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1743]
## Description

It is required to add language and `ActionType` if you want a regular code block.

## Context

Regular codeblocks (```) don't work as expected.

## Consequences

Opt-into `<Preview>`

**Comment by ti10le** [comment]
We had said when I changed this that collapseCode is used most often and is therefore default. CodeOnly is rarely used and should therefore be used with the specification of codeOnly.
I would like to keep it that way.

**Comment by ti10le** [comment]
@sebald should we do anything?

**Comment by sarahgm** [comment]
@sebald can this be closed? or what is this exactly about?

**Comment by sebald** [comment]
Yes, this can be closed :)
