### ISSUE TITLE
Coveralls gets no reports

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#175]
I thinks renaming the org has broken the submission of coverall reports ☹️
@viktoria-schwarz can you take a look at this, pretty please?!

See: https://coveralls.io/github/marigold-ui/marigold

PS: If you want, just move the job to GH Actions

**Comment by viktoria-schwarz** [comment]
The badge still has the old name, but I guess you don't want "reservix-ui" to appear in the URL? Frankly I don't know how to fix it, I read that after an organization renaming the repo is synchronized sooner or later but it hasn't happened yet for us

**Comment by viktoria-schwarz** [comment]
fixed by adding the correct token to CircleCI
