### ISSUE TITLE
Refa: use interfaces instead of `type`

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1758]
## Description

TIL we should prefer interfaces over intersections, because the later are harder for `tsc` to check.

See https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections

## Context

Typechecking will get slower with a growing code base, this we should use more interfaces.

## Consequences

Hopefully faster typechecking inside VSCode.

**Comment by sebald** [comment]
BTW this will also improve the experience for our users, if our takes can be faster interpreted!

**Comment by ti10le** [comment]
@sebald I have a problem in some components which have props including the same propName twice from different extensions. e.g. CheckboxInputProps
`interface CheckboxInputProps
  extends CheckboxIconProps,
    ToggleProps,
    ComponentProps<'input'> {}`

error and possible solution:
![Bildschirmfoto 2022-02-14 um 13 35 29](https://user-images.githubusercontent.com/59875255/155075839-82633f81-6893-4de3-a86e-af5ef91645aa.png)

Is it ok to use type here?

**Comment by sebald** [comment]
@ti10le sure changing that is for performance. we shouldn't have weird changes because of it.

Are you this isn't an actual error? Interfaces can be more strict. Is the `onFocus` in the ToggleProps the same type?

**Comment by ti10le** [comment]
Yes they are not identical. e.g.
COmponentProps<input> `        onChange?: FormEventHandler<T> | undefined;
`
ToggleProps: `  onChange?: (isSelected: boolean) => void,
`

I think also it's better to use type instead of weird types with interface
