### ISSUE TITLE
Update mdx monorepo to v2.0.0 and fix MDXProvider error

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1766]
## Description

If we update the Version from mdx-js/react and mdx-js/mdx to major v2.0.0 we got an error from wrapper.tsx. 

![image](https://user-images.githubusercontent.com/59875255/153367873-9188dbf9-5cb7-469c-a183-3915f71f7e9b.png)

## Context

Fix it to use the mdx-js major version.

## Consequences

Dependency mdx-js is up to date

**Comment by ti10le** [comment]
opened by dependency update: #1757

**Comment by sebald** [comment]
Need to wait for Gatsby MDX Plugin 😐

**Comment by sarahgm** [comment]
@sebald this issue can be closed or am I wrong?
