### ISSUE TITLE
docs: Navigation item shows green border by clicking an item

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1805]
## Description

Green border/outline is shown when you click on a navigation item. 
If you click on something else the green border is no longer shown on the item.
If you reload the page then you can see it again by clicking an item.

## How to reproduce

1. Go to docs
2. Click on item
3. See color
4. click somewhere else
5. see no color
6. reload page
7. click on item and see color again

## Expected behavior

No green outline/border color

## Screenshots

![image](https://user-images.githubusercontent.com/59875255/155511642-d255fe65-e47d-4d53-baeb-1fa55f321363.png)

**Comment by sebald** [comment]
That's not a bug BTW, just default browser behavior 😝

**Comment by ti10le** [comment]
> That's not a bug BTW, just default browser behavior 😝

@sebald for me it feels like a bug 😀

**Comment by sarahgm** [comment]
I try to reproduce it. It's just after I first use tab and don't click the focus away and when I reload the page and don't use tab first :D feels like a bug to me too.
