### ISSUE TITLE
Marigold Landing Page

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#1834]
## Description

We currently don't use the `/` (Landing page), we should make a fancy design or something with the Marigold logo and links to documentation and figma.

Example:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/985701/156731543-05edcd51-2c2d-477d-aa23-30e63135c3b2.png">

## Context + Consequences

Promote the Figma Designs.

**Comment by andres-dediego2** [comment]
Habt ihr schon meine Landing Page in Figma gesehen?? 
https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=710%3A10858 
Da könnten wir auch diese Doku + Figma links haben :)
