### ISSUE TITLE
New naming conventions for scalable CSS

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#1871]
## Description

Since we are using openProps and redesigning our layout components we realized that we need a better scaling of our theme values. E.g. size space etc.
We need more sizes than e.g.:
`  sizes: {
    none: 0,
    xxsmall: 16,
    xsmall: 32,
    small: 40,
    medium: 80,
    large: 120,
    xlarge: 160,
    xxlarge: 240,
  },`

these size indexes are not practical for more then 8-10 values.
Some other systems using numbers e.g.: size-01, size-02, ..

[Here](https://speckyboy.com/naming-conventions-sizes-scalable-css/) are some more expressions

## Context

We need more values than 
`  none: 0,
    xxsmall: 16,
    xsmall: 32,
    small: 40,
    medium: 80,
    large: 120,
    xlarge: 160,
    xxlarge: 240,
    huge: 320,
    epic: 480`  
and dont have enough words to describe them.

## Consequences

We can use more sizes or spaces to handle all use cases with our themes and components.

**Comment by ti10le** [comment]
I vote for that too, then we do it like this 👍🏼

**Comment by sebald** [comment]
Closed via #1833
