### ISSUE TITLE
Message component update

### ISSUE THREAD

**Issue by Andres-Dediego** [marigold-ui/marigold#2167]
Link to Figma: https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=582%3A119

Todos:
- Change the top and size spacing (Different for each size compact 40px, Standard 56px, expanded 72px and expanded with 2 lines 96 px)
- Change the headers color to white.
- It should be possible to align the text (left, center and right).  It should align together with the sorting icon.

- Typography style:
Titel: H3
Text: body p
- Icons: 24 px
- Colors: Rot, blau und yellow (click on inspector) 

Icons (SVG): 
![arrow_drop_down_FILL0_wght400_GRAD0_opsz24](https://user-images.githubusercontent.com/32389677/179931661-e1eebd8b-e38f-417c-b74f-6edcb543466b.svg)

![arrow_drop_up_FILL0_wght400_GRAD0_opsz24](https://user-images.githubusercontent.com/32389677/179931658-e7d6f96f-5f59-4f90-a70a-af48b791480b.svg)

**Comment by sarahgm** [comment]
Is this the Table or Message update?

**Comment by sebald** [comment]
@Andres-Dediego ping
