### ISSUE TITLE
Docu: Move code examples to `<Sandbox/>`

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2198]
Link: https://sandpack.codesandbox.io/docs/getting-started/install

Questions:
- How to pass in a certain Marigold Theme, so we allow for themes so witch in the examples
- Can we SSR it?

**Comment by benediktgrether** [comment]
*MDX Example:* https://blog.logrocket.com/build-interactive-blog-with-react-sandpack/

**Comment by sebald** [comment]
We had to build a remark plugin instead 🙈
