### ISSUE TITLE
React-aria throws hydration error in PropsTable

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2237]
## Description

when using the `<PropsTable>` component in our docs-next react-aria thows an error `Prop id did not match. Server: "react-aria-1-property" Client: "react-aria-3-property"` . 

## How to reproduce

1. Go to a docs-next page with a `<PropsTable>` component
2. open the console and see the error message

## Expected behavior

no error should be there

**Comment by sarahgm** [comment]
reference: https://github.com/adobe/react-spectrum/issues/2231

**Comment by sebald** [comment]
@sarahgm this might be caused by the table not being ready for strict nice. We should check if we still get errors since we had to disable strict mode anyway

**Comment by sarahgm** [comment]
@sebald  I get another one that says the tabIndex and data-key did not match  

- `Warning: Prop tabIndex did not match. Server: "-1" Client: "0"`(on Select, Dialog, Radio, Label ...) 
- `Warning: Prop data-key did not match.` (on Table)

but strangely enough not always when I reload the page.

**Comment by sebald** [comment]
Does not happen anymore with Next 13 🥸
