### ISSUE TITLE
Refactor breakpoints on useResponsiveValue

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2283]
## Description

`useResponsiveValue` uses three  different breakpoints, but actually they use four. one as default and then the other ones to specify the breakpoints. 

https://theme-ui.com/getting-started#responsive-styles

it should be clear what breakpoint we're on and on which it breaks. it was not so simple finding out.

**Comment by sebald** [comment]
We have to check if the following is correct:

https://github.com/marigold-ui/marigold/blob/e4e8bd332bce61125b761ba1ee0760bc10af86b4/packages/system/src/hooks/useResponsiveValue.ts#L26-L30

Maybe it should be `n+1` since "no media query" is also possible.

**Comment by sarahgm** [comment]
I think i do not understand this.  If I add the '+1' it doesn't make any changes.

**Comment by sebald** [comment]
Well I didn't check but I guess the hook currently does not accept the right number of values.

If we have 3 breakpoints, it should allow 4 values. So this check is not working correctly. We should verify this with a story though.
