### ISSUE TITLE
📄 Post 2.0 Docs

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2291]
## 🗒 Open ToDo's:
- [x] #2448
- [ ] Auto gen props table via https://github.com/styleguidist/react-docgen-typescript (e.g. use frontmatter.title to find the component file, pass resulting doc to mdx via source prop)
- [x] #2325
- [x] #2302

### about writing 🖊:
- [ ] Complete our Concepts and Principles (#144, #1742)
- [x] #2515
- [ ] Extend a Theme page
- [ ] Improve Fooundation docs

## Done ✅:
- [x] Include `h2` into Toc
- [x] #2445
- [x] Fix demos for `<Menu>`
- [x] #2387
- [x]  #2340
- [x] Where to put the Figma link!?
- [x] fix demo for `Tooltip`
- [x] #2377
- [x] Improve Lighthouse score
  - [x] Add aria-label to Navigation Button
- [x] #2355
- [x] Add active state to the current navigation Item 
- [x] Add intersectionObserver to Toc
- [x] Back to Top Button in the Docu #2389 
- [x] #2413
- [x] #2414
- [x] Extend a docs page for responsiveness
- [x] #2453

**Comment by benediktgrether** [comment]
- [ ] Add active state to the current navigation Item

**Comment by sarahgm** [comment]
add later a IntersectionObserver to TOC ?

https://codesandbox.io/s/infallible-borg-mqh9df?file=/src/App.tsx:2210-2218
https://blog.openreplay.com/creating-a-table-of-content-widget-in-react
https://usehooks-ts.com/react-hook/use-intersection-observer

**Comment by sarahgm** [comment]
I close this because unnessesary
