### ISSUE TITLE
Add Logout Icon

### ISSUE THREAD

**Issue by lauraNawrotzki** [marigold-ui/marigold#2344]
## Description

There is no fitting icon for visualising the logout yet.
Adding a third party library for a single icon would be bothering.

## Context

There is a specific icon inside the FIGMA designs, we'd like to use throughout our application.

## Use Cases 

Logout! And shutting things down 

## Consequences

Happy ACD Team

**Comment by sebald** [comment]
Do you have a link to Figma for us? :)

**Comment by lauraNawrotzki** [comment]
sure thing!
https://www.figma.com/file/6ki8baSp8kiDyCRG15fACY/Verwaltung-ACC-Wireframe?node-id=0%3A1

The one on the top right corner

**Comment by sebald** [comment]
@lauraNawrotzki Thanks, I pinged Andres for the source, since it's an 18x18 svg in Figma and is missing some props.

**Comment by sebald** [comment]
Small update:  waiting for the icon to be added to the Design System Figma files 🙂

**Comment by Andres-Dediego** [comment]
![power_settings](https://user-images.githubusercontent.com/32389677/186643319-8d872426-be8d-41cf-a450-6c0c5991b5c0.svg)

**Comment by Andres-Dediego** [comment]
So die Box ist 24x24 px und die icon ist 18x18 px
