### ISSUE TITLE
Menu Items only show correct after resize event in Docu

### ISSUE THREAD

**Issue by benediktgrether** [marigold-ui/marigold#2366]
## Description

If the Menu is toggled the position of the overlay is not set with top and left position attributes. 
The Menu Items will appear on the bottom of the page.

If i resize the window the position where calculated new and then i have a top and left position.

## How to reproduce

1. Go to Menu in Docu
2. Click on Menu
3. Resize the Window
4. You should see the menu

## Expected behavior

Menu Items should appear under the Menu

## Screenshots

![Bildschirmfoto 2022-08-26 um 12 34 46](https://user-images.githubusercontent.com/27921741/186885928-74b3f2fa-dad4-4889-a86e-3e6805825a52.png)

**Comment by sebald** [comment]
So there is no top/left/... set :-/

**Comment by sarahgm** [comment]
closed because it worked :D
