### ISSUE TITLE
Button min-width does not take icon into account

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2368]
## Description

Button with icon inside is allowed to shrink to a point where the icon is not really visible anymore.

## How to reproduce

```
<Button variant="ghost" size="small">
    <Info />
    Details
</Button>
```
Put this in a container such that the Button has not enough space, live demo: https://acc22.acm.reservix.net/devices
The icon in "Details"-Button is not visible on most screen sizes, if you simulate a very wide screen (using responsive tools) it appears.
<img width="134" alt="Bildschirmfoto 2022-08-26 um 13 18 17" src="https://user-images.githubusercontent.com/531872/186892369-53467de7-26d4-40b7-b571-0b0cfe84a0af.png">

**Comment by michael-p** [comment]
This still does not seemed to be working for me - did you test this with icon in a button?

**Comment by sarahgm** [comment]
@michael-p is in new release

**Comment by sarahgm** [comment]
can reproduce it, isn't there the question what should happen if a button (with or without icon) hasn't enough space?

**Comment by sebald** [comment]
In Michael's case the icon also gets smaller right? That's the flex again 🫠
