### ISSUE TITLE
Table with stretch=true breaks when space is too narrow

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2369]
## Description

`<Table stretch> ...` resizes automatically with available space but at some point it stops shrinking and breaks out of its parent container. Better and more responsive behavior would be to start scrolling horizontally at that point.

## How to reproduce

Go to https://acc22.acm.reservix.net/devices and resize your window to be very narrow. At some point the layout breaks.

**Comment by sebald** [comment]
@sarahgm was this solved? I think you mentioned something about this today ☺️

**Comment by sarahgm** [comment]
> @sarahgm was this solved? I think you mentioned something about this today ☺️

I have made the table scrollable when it's too small too display. Is that what is meant? 🙂

**Comment by sebald** [comment]
Yes, so let's close this 😎

**Comment by michael-p** [comment]
Seems to work only on smallest breakpoint but is needed regardless of screen size.

**Comment by michael-p** [comment]
This seems to be the problem: https://github.com/marigold-ui/marigold/blob/main/packages/components/src/Table/Table.tsx#L83
