### ISSUE TITLE
Card should have `overflow: none`

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2374]
## Description

If content of Card is too wide it just breaks out of the card and messes up the layout.

Also, this causes issues with Cards with no padding (see #2373) and the border-radius of the Card.

## How to reproduce

Put a very wide element inside a Card.

## Screenshots

<img width="1028" alt="Bildschirmfoto 2022-08-29 um 11 20 12" src="https://user-images.githubusercontent.com/531872/187168968-bb55d2ce-4895-400a-90a6-c42d1d597462.png">

**Comment by sebald** [comment]
@sarahgm I think this is fixed too, right?

**Comment by sebald** [comment]
@all-contributors please add @michael-p  for error ideas

**Comment by michael-p** [comment]
In which MR was this addressed? Does not work for me, and last change of Card component is 5 month ago...
