### ISSUE TITLE
Add `stretch` prop to Card

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2386]
## Description

Currently, `Card` is only as high as its content - it would be great if there were a way to specify `height: 100%` on it, that is, it should fill all available space. Similar to `stretch` prop on Stack.

Maybe this should also be added to all componentss, not just Stack and Card.

## Context

See second Card in screenshot:
<img width="1392" alt="Bildschirmfoto 2022-09-01 um 08 15 09" src="https://user-images.githubusercontent.com/531872/187844706-d8e348b5-3c36-47b3-a15e-8af89d28d5f2.png">

**Comment by michael-p** [comment]
not stale 🙄

**Comment by michael-p** [comment]
.

**Comment by sarahgm** [comment]
is this still relevant ? @michael-p

**Comment by lauraNawrotzki** [comment]
We still have to use our custom css for the card to take up all the space

**Comment by sarahgm** [comment]
close this because we found a solution
