### ISSUE TITLE
Add Accordion for Documentation

### ISSUE THREAD

**Issue by benediktgrether** [marigold-ui/marigold#2388]
## Description

For a better overview we should add accordions to the documentation in the faq section. 
The Questions should be the headline and always be shown. 
The answer is in the accordion and hidden. 

For this FAQ accordion we can check if we want to implemented this as structured data for future project ?
https://developers.google.com/search/docs/advanced/structured-data/faqpage

## Context

Structured content for better reading in the faq section. 
Not the amount of text if you go to this page. You online see the question and than you can choose the one you looking for.

## Consequences

Faster reading and searching for your faq your looking for.

**Comment by michael-p** [comment]
FYI: for ACC we also needed an accordion-style component and have already built our own (but not really reusable): https://acc22.acm.reservix.net/devices

**Comment by sebald** [comment]
Superseeded by #1687
