### ISSUE TITLE
Add `DateField` component

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2408]
## Description

Currently there are `TextField` and `NumberField` components but no `DateField`. One can use `<Input type="date" />` but this does not have a label, description or error. Another work-around (that we use) is `<TextField type="date" /> `. This works but is obviously very ugly :)

## Context

We need to be able to use date fields in forms!

**Comment by sebald** [comment]
You can use `<TextField>` for now: https://marigold-ui.io/components/text-field/#use-different-input-methods 🥸

**Comment by sarahgm** [comment]
https://react-spectrum.adobe.com/blog/date-and-time-pickers-for-all.html

**Comment by sarahgm** [comment]
related #2893 , so I close this
