### ISSUE TITLE
Add a badge to components: new/updated/beta/deprecated

### ISSUE THREAD

**Issue by benediktgrether** [marigold-ui/marigold#2414]
## Description

Add a badge to components and navigation to show if there any changes.
The Badge can have following status
* new
* updated
* beta
* deprecated

## Context
If we add badges to the Documentation other developer can see faster if there any changes with some of the component or is a component new or deprecated.

**Comment by sebald** [comment]
test

**Comment by sebald** [comment]
test test

**Comment by sebald** [comment]
@marigold-ui/acc ping!
