### ISSUE TITLE
Tooltip: add press as trigger

### ISSUE THREAD

**Issue by lauraNawrotzki** [marigold-ui/marigold#2450]
## Description

The tooltip has a trigger property, which we would like to add a press trigger to.

## Context

We'd like to use the tooltip on mobile devices like smartphones and tablets. On these devices, the tooltip can't be triggered by hover or focus. Therefore it would be great, if we could trigger the tooltip on press. 
**Important:** now the tooltip "listens" on hover **AND** focus by default. When the press trigger is added, it should not remove these triggers. So the tooltip would listen on hover **AND** focus **AND** press, when wanted by the user.

## Use Cases 

Make the tooltip useable on mobile

## Consequences

Better tooltips! :)

**Comment by lauraNawrotzki** [comment]
Would be sweet to have this feature ready for our next demo day in October if it's not too much to do :)

**Comment by sebald** [comment]
This is possible via the `open` prop. We added an example: https://github.com/marigold-ui/marigold/pull/2512

Note that this will make the tooltip a controlled component, you have to manage its state yourself.
