### ISSUE TITLE
Extend our Components Pages

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2453]
Components to edit. They should be structured as shown in [here](https://reservix.atlassian.net/wiki/spaces/DST/pages/1684279122/Inhalt+f+r+Component+Documentation)

### Layout
- [x] Aside
- [x] Aspect
- [x] Box
- [x] Breakout
- [x] Center
- [x] Columns
- [x] Container
- [x] Content
- [x] Divider
- [x] Inline
- [x] Split
- [x] Stack
- [x] Tiles

### Content
- [x]  Badge
- [x]  Card
- [x] Footer
- [x] Header
- [x] Headline
- [x] Icon
- [x] Image
- [x] Link
- [x] List
- [x] Message
- [x] Text
- [x] VisuallyHidden

### Forms
- [x]  Button
- [x] Checkbox
- [x] Input
- [x] Label
- [x] NumberField
- [x] Radio
- [x] Select
- [x] Slider
- [x] Switch
- [x] TextArea
- [x] TextField

### Overlay
- [x]  Dialog
- [x] Menu
- [x] Tooltip

### Application
- [x]  Provider

### Collections
- [x]  Table

**Comment by sebald** [comment]
Well done @sarahgm 👏🙇‍♂️
