### ISSUE TITLE
Script to create component template

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#247]
In order to enforce consistency and help with some gotchas, we should have a script that generates component a boilerplate.

It should

- generate a component folder inside ‘packages/components/<name>’
- Barrel file (index.ts) as well as component, test and story file
- each generate file should have the base content
  - Test: all common Tests (e.g. internals can not be overridden)
  - first story
  - component file: import Box, empty react component and props

**Comment by viktoria-schwarz** [comment]
Any ideas on how to implement this? Is inquirer an option?

**Comment by viktoria-schwarz** [comment]
As for default test cases I come up with the following:

* default variant and theme section are set
* accepts custom variant
* renders an instance of the desired HTML element
* internal styles cannot be overwritten

Optional:
* accepts custom other props defined for component

**Comment by sebald** [comment]
Sorry... didn't saw your comments. 

Yes, using `inquirer` adds some good DX to scripts. I also wouldn't bother to write the script in TS, because we would also need to use `ts-node` to execute it.

**Comment by viktoria-schwarz** [comment]
What does it mean that we need to use `ts-node`?
