### ISSUE TITLE
Make the text on the tables selectable for copy

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#2484]
Link to Figma:
https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=2387%3A1929

Todos:
Make the text on the tables selectable for copy, or at least create a variant to select if the text may be selectable or not

**Comment by sebald** [comment]
Already implemented, see https://github.com/marigold-ui/marigold/pull/2399
