### ISSUE TITLE
Let icons support size and fill prop

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#249]
--> continuation from 192 

the icons must be able to pass the two props to the SVG component.

**Comment by ti10le** [comment]
Hey @sebald @viktoria-schwarz 
How should we test the icons? I think it's too much to write the same test for every Icon. An example with one icon should be the best way. What do you think? (Actually jest ignores the icons folder)

**Comment by sebald** [comment]
Yeah, I guess not having tests for icons is fine.
