### ISSUE TITLE
Write guidelines and implement do and don'ts

### ISSUE THREAD

**Issue by benediktgrether** [marigold-ui/marigold#2515]
We need Guidelines for our component when we can Use the component or a property of the component and when we don't use this component or property.

---
- [ ] Buttons - When do we use which button? When to use the Ghost Button? 
- [ ] Numberfield -  When we use the hideStepper Property?
- [ ] Radio - When we use the Horizontal Direction? 
- [ ] Badge - What status messages should a badge communicate?
- [ ] Body - How to use the body in the correct way.
- [ ] Card - How to use the Card.
- [ ] Footer - How to use the Footer.
- [ ] Header - How to use the Header.
- [ ] Message - Did we had many Messages? Or only the more Critical Message that we will show? If we shown differente Message, did we had a Priority which message is shown first?

## When we use the disabled property?
- [ ] Menu 
- [ ] Buttons
- [ ] Checkbox 
- [ ] Input
- [ ] Radio
- [ ] Select
- [ ] Slider
- [ ] Switch

**Comment by sarahgm** [comment]
@benediktgrether @sebald @andres-dediego2 maybe we can combine this also with the mini-workshops?

**Comment by sebald** [comment]
Second that, this works definitely be part of the outcome

**Comment by andres-dediego2** [comment]
Yes, many of the stuff we can discuss in the mini-workshops
