### ISSUE TITLE
Farbe bei Headers und Tabellen 

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#2517]
## Overview

| Component Name | Card (Text)             | Theme      | B2b
| -------------- | ---------------- | ---------- |
|                |  | `core/b2b` |

## Appearance Update 

**Figma Link:** [TAble](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=4345%3A8044)
Card: https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=3547%3A4992

- ...

## Behavior Update 

- ...

**Comment by sebald** [comment]
Checked. Already done
