### ISSUE TITLE
Hover color  on tables 

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#2518]
## Overview

| Component Name | Table             | Theme      |
| -------------- | ---------------- | ---------- |
|                |  | `core/b2b` |

## Description

The hover is not working on tables (at least in the Marigold version that ACC Team updated)

## Appearance Update 

**Figma Link:** [Table](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=4345%3A8044)

- ...

## Behavior Update 

- ...

**Comment by sebald** [comment]
We talked about this :D already working. Next time please split this into a bug report AND a change request.
