### ISSUE TITLE
Select component with icons

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#2519]
## Overview

| Component Name | Type             | Theme      |
| -------------- | ---------------- | ---------- |
|                |  | `core/b2b` |

## Description

It is not possible to set icons on the select component as used on the Login
If this ticket is repeated just ignore it 

## Appearance Update 
Create a variant where you can set icons on the select.

**Figma Link:** [Select](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=2748%3A3081)

- ...

## Behavior Update 

- ...

**Comment by sebald** [comment]
We need more information about the behavior, usage and use cases.
