### ISSUE TITLE
Tables are not responsive

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2596]
## Description

Tables to not shrink beyond a certain minimal size horizontally and hence "break" layout on small screens. We only tested with `stretch = true`.

## How to reproduce

See: https://replit.com/@michaelpx/Responsive-Marigold-Table
Resize your window. If there is enough space horizontally, table stretches and one can scroll the parent `Box` vertically but not horizontally, as expected. If the window is too small horizontally, the table should scroll horizontally. Instead what happens is that it stays at its minimal size and the parent `Box` starts scrolling horizontally due to overflow. This can be seen by looking at the blue box above the table. This should *not* move horizontally.

Real-world example: "Veranstaltungssuche" here: https://acc22.acm.reservix.net/devices

**Comment by sebald** [comment]
A `<table>` HTML element as is can never be responsive (as in it will show scrollbars), this is only possible by wrapping it with a container. This also works (as I would expect) in your example:

![Kapture 2022-10-26 at 15 34 39](https://user-images.githubusercontent.com/985701/198040691-c5feeea3-0bf9-464c-9039-bac69acf454f.gif)

We use this behaviour in our docs where the `<Table>` lives inside a container with a `max-width`. See:

![Kapture 2022-10-26 at 15 39 03](https://user-images.githubusercontent.com/985701/198041471-1f745df9-14e0-46f6-921a-70cafbacfb0b.gif)

I guess you can achieve the behavior you want when we implement https://github.com/marigold-ui/marigold/issues/2537 ?

**Comment by sebald** [comment]
@michael-p This is what you could do we `<Clamp>` (currently implementing this):

![Kapture 2022-10-31 at 13 05 17](https://user-images.githubusercontent.com/985701/199004935-08baa517-b1a1-4750-8f0e-1a1bfa2d3844.gif)

Is this what you are looking for?

**Comment by michael-p** [comment]
Yes this looks like the behavior we'd like to see! :)
Have you thought about making this a built-in behavior of `Table`? I guess many/most applications will want to have this by default.
Also, other features like a fixed, non-scrolling table header  might be hard to implement in the future if the scrolling behavior is handled by a separate parent component.

**Comment by sebald** [comment]
@michael-p yeah, I guess our designer really need to update and extended the specification for table. Currently the spec is really lacking any information about this stuff 🙈
