### ISSUE TITLE
Support `<Tiles>` to not expand in width

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2603]
## Description

Currently the children of `<Tiles>` will always take the available width (`1fr`) and only have a lower bound (`itemMinWidth`). There is no way to have children to stay at a certain width. This is especially useful if you have multiple `Tiles` on a page an want them to look the same.

## Proposal

Expand the API with properties to change from stretching to the available width to a given width.

## Implementation

Change grid template. Currently: 

```js
`repeat(auto-fit, minmax(min(${itemMinWidth}, 100%), 1fr))`
```

to 

```js
`repeat(auto-fit, minmax(min(${width}, 100%), ${width}))`
```

**Comment by sarahgm** [comment]
PS: also change API `gridAutoRows` -> `equalHeight`

**Comment by sebald** [comment]
So here is what I found out:

Without the `minmax(..., 1fr) the tiles will be exacly as wide as `itemminWitdh`

We need to have two "modes" -> a fixed grid -> use `tilesWitdth` AND a fully responsive one with minimal widths (like we one implemented)

This actually only makes a difference when you have less tiles than the width of the container.
If you have less tiles than fit in a row they will share the available space equally.

**API:**

- tilesWidth + minTilesWidth (can have only ONE)
- tilesWidth + mode = fixed / fluid

**Comment by sebald** [comment]
going with `stretch`! :D
