### ISSUE TITLE
Allow `Menu` to be wider than its trigger

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2648]
## Description

Currently a `Menu` is always exactly the width of its trigger (typically a `Button`). However, for scenarios where the menu is used as some kind of popup-menu it is necessary that the menu can be as wide as needed to display its menu items.

Current:
<img width="239" alt="Bildschirmfoto 2022-11-21 um 09 18 53" src="https://user-images.githubusercontent.com/531872/203014627-bcf2ec8f-b228-493b-80d7-a650e87f0a34.png">

Wanted:
<img width="305" alt="Bildschirmfoto 2022-11-21 um 09 18 38" src="https://user-images.githubusercontent.com/531872/203014669-e4ff0009-38b0-4411-bba1-aa926ac94cbf.png">

## Proposal

Menu width should be determined by its items, not the trigger. I don't know if there actually is a use-case for the current behavior but if yes, then maybe add a prop to opt-in to the old behavior?

**Comment by michael-p** [comment]
@sebald Do you think it will be possible to resolve this within the next 2-4 weeks? We already have a MR open that uses `Menu` and hence looks broken but we're inclined to merge it anyway as long as you are confident that this issue can be resolved in Marigold before the ACC launch. Would be great to know your assessment here! :)

**Comment by sebald** [comment]
This is what it looks like after the patch. We position it to the bottom left for now. Is that fine with you? 🙃

![image](https://user-images.githubusercontent.com/985701/203772915-6febec04-7905-48bb-9fab-9ace09e81efe.png)

**Comment by michael-p** [comment]
As long as it stays/flips within the screen's bounds it's fine! :) The button I took the screenshot from is at the very right border of the screen, that's why I had the menu positioned to the left.
Thank you! :)
