### ISSUE TITLE
Huge gap in Message headline when the text is too long

### ISSUE THREAD

**Issue by lauraNawrotzki** [marigold-ui/marigold#2650]
## Description

When there is not enough space and the text for the message headline is too long, the headline breaks into a new line, but there is a huge gap in between.

## How to reproduce

Create a message in a limited space with a longer headline.

## Expected behavior

The headline breaks into a new line with a normal sized gap (like the normal line height space in a Text)

## Screenshots

![Screenshot 2022-11-24 at 10 59 08](https://user-images.githubusercontent.com/104084537/203754594-738532a4-c845-42d3-9d7a-d4f7d175db45.png)

**Comment by sebald** [comment]
![image](https://user-images.githubusercontent.com/985701/203772629-cd4e5f67-fecb-4f03-88b4-676f3c07ac04.png)

**Comment by sebald** [comment]
The Icon is also responsive ... nice 🫣
