### ISSUE TITLE
Select in Table: Table scrolls to the bottom after selection

### ISSUE THREAD

**Issue by lauraNawrotzki** [marigold-ui/marigold#2692]
## Description

In the ACCv3 we have the famous table with select fields inside of the last column.
After selecting something or nothing from the select menu, the table scrolls all the way to the bottom and
the select field inside of the last column has a focus.

## How to reproduce

This is a problem to the ACCv3 and I wasn't able to reproduce this in a replit.

Since the site is not live yet, if you want to see the behaviour yourself do the following:
- checkout the branch (we sent the name to you)
- login
- go to "Profile und Geräte"
- you don't have to select an event
- click on "Geräte"
- select something inside the table

## Expected behavior

The table should not scroll down after the user selected something and the last select field should not be focused.

**Comment by benediktgrether** [comment]
@lauraNawrotzki can we close this issue? I think it's working now with the changes from the keys names?
