### ISSUE TITLE
`<Menu>` rename `onSelect` to `onAction`

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2728]
## Description

Using `onSelect` as handler for the `Menu` component is hard to understand. It doesn't reflect the intent enough, which is actually to execute an action after a user clicks on a menu item...

## Proposal

Rename `onSelect` to `onAction`

## Documentation

- [x] Add an example to the docs that shows how to use `onAction` and maybe remove the example that sets state...

**Comment by sarahgm** [comment]
**Note**: onAction is in react-aria on the button https://react-spectrum.adobe.com/react-aria/useMenu.html#menuitem in our case its on the menu item. 

and I'm not sure what is meant by the example which should replaxe the example that sets state.

and does that mean that the dot component should be first implemented? :)

**Comment by sebald** [comment]
@sarahgm the onSelectionChange is on the menu too, isn't it 🤔  Which dot component?

**Comment by sarahgm** [comment]
@sebald Yes it is, I mean point two of the to dos. I don't understand.

**Comment by sarahgm** [comment]
@sebald  maybe this "Replace the settings dot example with this component 😅" belongs to this dot component issue

**Comment by sebald** [comment]
...yes ☺️
