### ISSUE TITLE
Introduce a "Dot Menu"

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2730]
## Description

[Dot Menus](https://tyler-technologies.github.io/design-guide-gallery/kebab) will appear in a lot of different apps by different teams. To prevent them from wiring the icon and the menu together themselves we should do it for them.

## Proposal

- Introduce a `<DotMenu>` (naming pending) that uses the `<SettingDots>` icons as trigger.
- We might need to introduce a button variant with a transparent background.

 

- [x] Replace the settings dot example with this component 😅

**Comment by sarahgm** [comment]
I can't open the link 🧐

So as I understand right, it should be a new Component - not a variant from the Menu?

**Comment by sarahgm** [comment]
@sebald  isn't the button variant with the transparent background the "text" variant???
