### ISSUE TITLE
Refactor CSS of label positioning

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2841]
## Description

We allow to position a label on top of an input (default) but themes, like the `theme-core` can also place the label on the left side. Especially the later one is channeling because all labels must have the same width in a form. This is why we introduced `<FormGroup/>`. Currently there are some placement issues with the left aligned label we want to adress:

- We need a default label width because otherwhise the label will collapse sometimes
- (We need more control over the placement)

## Proposal

![image](https://user-images.githubusercontent.com/985701/222661528-5be4b16c-9c72-4a0c-8f3d-6321b3fa9c5b.png)

- Use CSS grid to make easier to switch between the two layouts, using `grid-area` (see image above)
- Maybe introduce a `labelPosition` prop on the `FieldGroup`?

**Comment by sarahgm** [comment]
think we can close this with #2911 reasons
