### ISSUE TITLE
Fix field states in `b2b-theme`

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2843]
## Description

The field states are currently not always correct (e.g. focus + hover). This is due to the fact that we tried to use `box-shadow`, since the original design switch between 1px and 2px borders. This would make our layouts jump.

## How to reproduce

1. Go to `<TextField>`
2. Focus `<TextField>`
3. Hover `<TextField>`
4. See error -> weird

## Expected behavior

Have only one state showing up.

## Screenshots

Has both grey AND orange border:

![image](https://user-images.githubusercontent.com/985701/222663472-017a923e-bc6f-40b7-b0c7-a76d866b4a29.png)

**Comment by sebald** [comment]
@andres-dediego2 I would like to also start using a different color for the `focus` state, since the current one is not really visible. 

![image](https://user-images.githubusercontent.com/985701/222663853-08faeaf9-3664-4b39-afa6-0fcad7ecaa65.png)

**Comment by andres-dediego2** [comment]
Here is a new color for the focus state that do not interfere with the actual palette. 
blue-20 or #C1F0FC

https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=7137%3A13701&t=2rsM01vQcKf8I4fD-1
