### ISSUE TITLE
Create new component: date field 

### ISSUE THREAD

**Issue by YannicHermannRX** [marigold-ui/marigold#2893]
TEST ISSUES - Feel free to add feedback 

## Description

Because of the high usage of selecting dates in our products and general missing of this component in the design system, we need to build the new component _date field_.  

## Proposal

The component date field enables user to pick a specific date via manual input or through an additional calendar (which is defined in another issue, link will be updated). The manual input is always allowed and from UX-perspective especially important, when the date is already known by users e.g. birthday. 
(For e.g. scheduling smth. which is depending on a specific weekday, a calendar is more likely to use.)  

## Behavior

The default state is _enabled_. Only numbers allowed. When clicking the date field, state change to active and the first part of date field text is marked (DD). If the input is bigger than 3, the marker switches directly to the middle part of the date (MM) - otherwise after two numbers. If the input is bigger than 1 in the middle part, the marker switches directly to the last part (JJJJ). 

If date is already selected by user and needs to be changed or deleted: On click whole input field text is marked and can be deleted via backspace. State switch to _enabled_. If user is clicking in a specific part of input field text (DD/MM/JJJJ), the specific part is marked and can be deleted via backspace. If new input is made, the old one is overwritten.

The input is confirmed through an additional component (e.g. button). 

For more detailed information about the behavior or information about styling and spacing read the [specification](https://www.figma.com/file/HkoXCRkoUbCxRbg1CuaTDx/Design-System-Workflow?node-id=644%3A31307&t=uept6Y19hJEH35ou-1
)

**Comment by sarahgm** [comment]
related #2408

**Comment by sarahgm** [comment]
closed #2947
