### ISSUE TITLE
[react-aria] Issues

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#2910]
This issue contains a summary of issues and missing features we encountered when working with `react-aria`. We do this to keep track of some fixes and workarounds we did.

- onPointerUp in `MenuItem`
- Popover can not disabled `onBlur`
- useCalender can not change the format of the week days
- custom useAccordionItem (missmatches with the TreeState and Collections SelectionManager, not supporting JSX children)

**Comment by sarahgm** [comment]
is this still relevant? @sebald

**Comment by sebald** [comment]
We can also gather this in confluence
