### ISSUE TITLE
Add TailwindCSS in Marigold

### ISSUE THREAD

**Issue by sarahgm** [marigold-ui/marigold#2917]
## 🗒 Open ToDo's:

- [x] simplify design tokens for B2B
- [x] convert emotion styles to tailwind for B2B
- [x] add test for `system/utils/get`
- [x] ignore coverage for `create-preset`
- [x] deprecated Box?
- [x] delete token package
- [x] delete theme-old after B2B migration is done
- [x] #3022

## -> Components lists here  #2961
- [x] done

## System finished
- [x] Box (Test, Story, Component)
- [x] useResponsivevalue (Test, Story, Function)
- [x] useTheme (Test. Function)
- [x] useComponentStyles (Test, Function)

## ✅ Done:
- [x] Tailwind works in all components 
- [x] Tailwind Presets 
		-  every theme should be a preset
- [x] finish core theme
- [x] Handle extending theme 
		- maybe solved through presets
		- create-preset package
- [x] Tailwind on Storybook
		- works with theme switcher (Badge core + unicorn)
- [x] Build Tailwind with tsup in theme.
		- type safty makes problems
- [x] Build CSS in components (Layout Components) for things like spacing/alignment
		- kinda works I have to save the classNames as safelist and an ugly if else condition
- [x] create a theme 
- [x] parts as slots
- [x] useResponsiveValue
- [x] how to handle css selector classes // do we need them?!
- [x] handle stacked theme in storybook not 100% sure
- [x] HelpText (Test): some tests didn't work - can colors or size set via theme anymore?

related Issue is: #2153

**Comment by sarahgm** [comment]
@sebald  notice: data attributes must be written as `data-[disabled]` for example. With shortcuts like this: https://tailwindcss.com/docs/hover-focus-and-other-states#data-attributes  it is not possible. So how do we handle it? Should we just keep guessing if it has an data or not. Like in Button it just work with `disabled:` selector 🤷‍♀️

**Comment by sarahgm** [comment]
root styles on body

**Comment by sarahgm** [comment]
`tvMerge` sequence is important so first we should write the base styles within components than the classNames from the theme

**Comment by sarahgm** [comment]
linear gradients -> Select

**Comment by sarahgm** [comment]
tailwind listbox

**Comment by sebald** [comment]
Not sure I follow, show me tomorrow? :)
