### ISSUE TITLE
Slack Notification about Build Status

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#294]
Until recently we used an Orb in CircleCI for sending a notification to the slack channel #marigold_status, but since we have moved to GitHub Actions, we don't send notifications anymore.
I suggest to re-vive the channel and implement slack notifications e.g. via https://github.com/voxmedia/github-action-slack-notify-build

**Comment by viktoria-schwarz** [comment]
@sebald I need to add a new App in Slack for that to get the token etc., so you need to give me admin rights for that at some point :)

**Comment by sebald** [comment]
Noes can do, but I can give you a token, I guess? 😄

**Comment by viktoria-schwarz** [comment]
Yes I guess the token is what I need to implement it in the GH Actions. I need the app as described in the bottom here https://github.com/voxmedia/github-action-slack-notify-build :)

**Comment by viktoria-schwarz** [comment]
closing as we don't create the token now
