### ISSUE TITLE
Creating Accordion for the B2B Theme

### ISSUE THREAD

**Issue by andres-dediego2** [marigold-ui/marigold#2959]
## Overview

| Component Name | Type             | Theme      |
Accordion

## Description

ACM Requires the created Accordion for the "Core" Theme, but with the B2B Style. This in order to update their already used 
Additionaly they would like to have an Optional Subtitle next to the Title (see Example in Figma)

## Appearance Update 
It should follow the B2B Style (see figma File)

**Figma Link:** [Accordion](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?type=design&node-id=8551%3A14673&t=KvtWfzukUKwSYD49-1)

- ...

## Behavior Update 

- Attached are 2 images, that show how did I create the structure for the elements that can be shown or hidden.
- It sould be possible to insert other objects inside a container under the tittle, when the accordion is expanded, for instance a box, a table, or anything in between.

- Responsiveness: it should be possible to be used with a grid, so that the developer can fill the whole space inside the container, and this one should be flexible.
- ...

### New

<img width="686" alt="Screenshot 2023-05-04 at 11 49 14" src="https://user-images.githubusercontent.com/34473133/236172017-c50f5c61-e711-43af-8d73-d3a39c7fea3a.png">
<img width="701" alt="Screenshot 2023-05-04 at 11 49 27" src="https://user-images.githubusercontent.com/34473133/236172021-eaf4de3b-6ed7-48bd-8a97-a50778afed65.png">

**Comment by sarahgm** [comment]
is in Jira
