### ISSUE TITLE
Design & Component update - Button with icon

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#297]
We already have button with icon component. Issue to this: see #146 

[Button Figma styles](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=428%3A0)

**Problem** - two things are missing right now:
- we have to find a solution for the small button default size (at the moment 24px icon size). Default icon size is `24px`. Small button icon should have `20px`.
- If a button has an icon, padding-left should be: `button.small: 12px` instead of 16 and `button.large: 24px` instead of 32.

**Comment by ti10le** [comment]
@viktoria-schwarz @sebald this is a special b2b-theme issue. With the button API we have, we cant implement this like in the figma design example. Should we set this to ready or remove it for now?

**Comment by sebald** [comment]
It can only be ready if we have a solution.

**Comment by ti10le** [comment]
Maybe we open it again if we have a new design for the icon button
