### ISSUE TITLE
Documentation: Required Migration for Tailwind

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#3022]
Gather all things that have to be changed/migrated/updated/...

# The List

- [ ] Setup Tailwind with NexJS 
- [ ] Migrate theme from Emotion to Tailwind 
- [ ] Create preset for Documentation theme (do we need that?)
- [ ] Migrate tokens (colors, typography , root styles,  all open-props) to Tailwind => referes to `@marigold/tokens` which is deleted in `tailwind-variants`
- [ ] Migrate components (PropsTable, AppearanceTbale, etc.) to Tailwind
- [ ] Demos are using `Box` -> needs migration to use Tailwind and `className`
- [ ] How can we switch themes with Tailwind in our documentation?
- [ ] How can we load inside the `docu theme` our `marigold themes`?
- [ ] go through mdx files and eventually adjust text or pages // also delete old pages for example  `styling.mdx`, `box.mdx`, `css-in-js.mdx` etc.

---

- [ ] Can we use Sandbox for code Demos? (How to Switch themes? How to use the latest, not published version of Marigold?)

**Comment by sarahgm** [comment]
https://dev.to/shreyvijayvargiya/theme-toggle-using-tailwind-css-in-just-3-steps-1eij

**Comment by sarahgm** [comment]
**Sandpack**
How to switch themes in Sandpack? -> https://github.com/codesandbox/sandpack/tree/main/sandpack-themes

**Comment by sarahgm** [comment]
Is in this case meant to update to next 13 or stay with 12?

**Comment by sarahgm** [comment]
Sandpack with Tailwind: https://sandpack.codesandbox.io/docs/getting-started/usage#static-external-resources
We have to include all or theme files I think as option
