### ISSUE TITLE
[Challenge] Create an SSR/SSG example

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#360]
Since we now have enough components to build something, let us take the current state of the component library for a test drive (and also generate some documentation).

## Challenge

- [x] Show a predefined list of groceries.
- [x] Each item in the list can be (un-)checked (with `<Checkbox>` or something).
- [x] Option to add a new grocery.
- [x] Use the `b2b` theme.
- [x] If all groceries are checked, show a "done" message.
- [x] App must use SSR/SSG (e.g. nextjs or gatsby).

*PS: Yes, this is more or less a TODO-App!*

## Proofs

- [x] It is possible to use `marigold` when doing SSR/SSG.
- [x] Our API is not too complicated. At least WE can use it.

**Comment by viktoria-schwarz** [comment]
Done, code accessible on https://github.com/viktoria-schwarz/marigold-test :heavy_check_mark:

**Comment by ti10le** [comment]
https://github.com/ti10le/marigold-groceries-example ✔️

**Comment by ti10le** [comment]
@viktoria-schwarz what do you think about the proofs?
cc: @sebald 

"It is possible to use marigold when doing SSR/SSG.": Yes
"Our API is not too complicated. At least WE can use it.": In my opinion the components are easy to use.

**Comment by sebald** [comment]
Great work! Your solutions are different from one another, but they are both really really good!

## Notes:

- https://github.com/viktoria-schwarz/marigold-test/blob/03ba6ce91dc433fc2bde33f0fa2e3ab105f7ac14/src/pages/index.js#L54
  This should (in the future) be solved by a layout component!
- https://github.com/viktoria-schwarz/marigold-test/blob/03ba6ce91dc433fc2bde33f0fa2e3ab105f7ac14/src/pages/index.js#L60
  https://github.com/ti10le/marigold-groceries-example/blob/56c3da2ec2c2b42b7cf467e18599eb78ac7a7669/src/pages/index.js#L51
  Is this style applied? Because it shouldn't. We should not allow this, haha!
  Would you want a API like `<Text color="white"/>` here? Where `white` is inferred from `colors.theme`?
- https://github.com/viktoria-schwarz/marigold-test/blob/03ba6ce91dc433fc2bde33f0fa2e3ab105f7ac14/src/pages/TodoListItem.tsx#L12
  https://github.com/ti10le/marigold-groceries-example/blob/56c3da2ec2c2b42b7cf467e18599eb78ac7a7669/src/pages/index.js#L43
  Thought that we will not allow something like this. Is that passed through?
- https://github.com/viktoria-schwarz/marigold-test/blob/03ba6ce91dc433fc2bde33f0fa2e3ab105f7ac14/src/pages/AddTodoForm.tsx#L23-L36
  This is so great that this works. Good work you both!

## Deploy?

I would like you two to deploy it to a Github page and share it in the internal portal channel, so the others can see your great work! :)

-> https://github.com/marketplace/actions/gatsby-publish

**Comment by viktoria-schwarz** [comment]
I agree that our components were easy to use for this specific example. The text color could (previously) not be changed except using the css prop, but I added the textColor prop lately (https://github.com/marigold-ui/marigold/issues/415). I also agree that we should be able to use theme colors (like colors.gray60 or so).
Do you mean the css in your third question? It works because the used property ("color" in Timo's example) is NOT previously defined in the theme. If it was specified in the theme, it wouldn't work...

I'll get ready for deployment now  :muscle:

**Comment by ti10le** [comment]
published: https://ti10le.github.io/marigold-groceries-example/
