### ISSUE TITLE
Getting Started - Overview - Click on FAQ Card redirected to 404 Page

### ISSUE THREAD

**Issue by benediktgrether** [marigold-ui/marigold#4347]
## Description

Hey everyone, i hope you doing well?

When i click on the FAQ card on the Getting Started Overview i get redirected to a 404 Page. 
When i click in the Navigation on FAQ i got redirected to the FAQ Page

## How to reproduce

1. Go to https://www.marigold-ui.io/getting-started/overview?theme=core
2. Click on FAQ Card 
3. Got redirected to 404 Page

## Expected behavior

Get redirected to https://www.marigold-ui.io/getting-started/faq?theme=core

**Comment by aromko** [comment]
Thanks for the notification. We are working on it and it will be fixed in the next version!
