### ISSUE TITLE
Improve API of `createStyles` for common use cases

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#595]
Currently setting up the hook is a two step process (1) variant base and normalization (2) actual hook. This is bad for end users. A regular hook would be better. Also, it would be nice if it could handle an additional `className` and append that to the resulting `classNames` string.

Can we remove the setup step and still have a good API for the hook?

**Usage**

```js
const classNames = useStyles({ className, variants, ...styles })
```

**API**

- **className (string):** append to resulting classNames
  Why? We need to be able to easily add "external" CSS classes if necessary.
- **variants (string|string[]):** list of variants from theme to apply
  Why? In some cases (buttons) we need to support multiple variants. Instead of specifying the base variant we can just `base.${variant}` ... maybe?
- **...styles:** custom styles that are interpolated through theme-ui  

---

We could also add a "variantBase" or similar to the parameters of `useStyles`.

**Comment by sebald** [comment]
Instead of a theme section we'd have something like this:

```jsx
import { useStyles, system } from '@marigold/system';

const Component = ({ variant = 'body', children, ...props }) => {
	const className = useStyles({ color: 'red', variant: `text.${variant}` });
	return (<div className={className} {...props}>{children}</div>);
};
```

**Comment by ti10le** [comment]
I will create a PR with the change from createStyles to useStyles. The difference is that you have to give the themeSection like in the example above. Section will be removed from the hook.
createStyles.tsx will be named as useStyles.tsx
