### ISSUE TITLE
Add normalization to useStyles Hook

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#609]
In #595 we made a new hook without using createStyles. Now we use directly the hook useStyles.
Since this point normalization is missing.

**Comment by sebald** [comment]
-> `getNormalization('a')`

**Comment by viktoria-schwarz** [comment]
We use [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) to look up the HTML Element and add the styles.

**Comment by viktoria-schwarz** [comment]
Make it applicable to only one element; rewrite function so it doesn't manipulate the given input. Adjust the tests (no array of elements anymore)
