### ISSUE TITLE
Remove circular dependency

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#728]
#860 introduced a small bug: `system` and `components` depend on each other.

https://github.com/marigold-ui/marigold/blob/ce98a8c12ea58a9d7ff88c929d3f31fe83f97265/packages/system/src/normalize.ts#L1

This import is not really necessary, maybe just move the type to `system`? :)

**Comment by viktoria-schwarz** [comment]
I don't think we need the type at all, I will just fix it.
