### ISSUE TITLE
Chore - fix import paths

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#816]
Replace all absolute import paths inside a package.

Edit: remove absolute paths from tests and stories files aswell

**Comment by sebald** [comment]
@viktoria-schwarz I think this is done, right? :)

**Comment by sebald** [comment]
Why the reopen? :-O

**Comment by viktoria-schwarz** [comment]
good question, last week I had a thought about it but now I can't remember -_-

**Comment by viktoria-schwarz** [comment]
Is it a problem we should tackle that the icon package requires the components package?
