### ISSUE TITLE
Design update - Slider

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#835]
Current Version:
- simple Slider component with variant prop

-> [Figma Design](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=845%3A1254)

**Todo**:
- add variant for Slider to show: `default`, `active` and `disabled`

**Comment by ti10le** [comment]
Added styles for firefox and webkit (chrome, safari, opera). One problem is that theres no webkit support for progress styling (the styles left from the thumb) like firefox or IE. [See here...](https://www.quirksmode.org/blog/archives/2015/11/styling_and_scr.html#:~:text=Filling%20the%20track-,progress,-In%20my%20example)

**Comment by ti10le** [comment]
firefox:
![image](https://user-images.githubusercontent.com/59875255/133231067-ef714116-cd1e-466c-834c-2d67964991ba.png)

chrome:
![image](https://user-images.githubusercontent.com/59875255/133231123-f80efa30-4046-4ae6-a17b-bd75bdc9a2b6.png)

**Comment by ti10le** [comment]
I would say the problem is currently too small to invest so much extra time in it. What do you think @viktoria-schwarz @sebald?
More info at my Draft PR

**Comment by ti10le** [comment]
What do you think about this @sebald @viktoria-schwarz ?

**Comment by sebald** [comment]
Will look into it this week

**Comment by sebald** [comment]
let's merge and add a bug report for chrome?

**Comment by ti10le** [comment]
Ok 👍🏼
