### ISSUE TITLE
Support loading google fonts?

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#882]
Do we want to support something like this: https://www.npmjs.com/package/gatsby-plugin-web-font-loader

**Comment by sebald** [comment]
I think this should be done in user land. There are already good options:

- https://github.com/nfl/react-helmet
- https://nextjs.org/docs/api-reference/next/head

**Comment by sebald** [comment]
What do you think @viktoria-schwarz @ti10le

**Comment by viktoria-schwarz** [comment]
I still support the idea but I still don't know how to do it exactly. So I can't say anything about it

**Comment by sebald** [comment]
We'll close this for now.
