### ISSUE TITLE
feat: improve `useStyle` types

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#887]
## Description

Currently the input type of `useStyles` is very lax and allows the index type (`[key: string]: any;`). This allows for some silly mistakes and does not use the full potential of TypeScript.

## Context

In order to harden the types we would like to do something like this:

```ts
export interface StylesProps extends Omit<CSSObject, 'variant' | 'element'> {
  element?: ElementType;
  variant?: string | string[];
}
```

Sadly this doesn't work because of the index type of `CSSObject`.

```
Property 'element' of type 'ElementType<any> | undefined' is not assignable to string index type 
'StylePropertyValue<string | number> | null | undefined'.
```

Using `any` for `element` also does not work. `useStyles({ element: Component })` will result in the following error:

```
Type 'ComponentClass<any, any>' is not assignable to type 'ThemeUICSSObject'.
          Index signature is missing in type 'ComponentClass<any, any>'.
```

We basically ran into this https://github.com/microsoft/TypeScript/issues/17867

## Use Cases

```ts
​useStyles​(​{​ element​,​ css​,​ className, variants ​}​)
```

```ts
type UseStyleInput = {
	element?: ElementType;
	css?: Omit<CSSObject, 'variant' | 'element'>;
	variants?: string | string[];
	className?: string;
}
```

## Consequences

We would have a very type-safe API. But would have to refactor a lot of code.

**Comment by sebald** [comment]
A solution would be to change the API. E.g.

```ts
useStyles({ element, css, className })
```

or 


```ts
useStyles(stylesIncludingClassName, element)
```

**Comment by viktoria-schwarz** [comment]
Hmmm. If we change the API to `useStyles({ element, css, className })` that would mean something like this

```typescript
export type StylesProps = {
  element?: ElementType;
  css?: Omit<CSSObject, 'css' | 'element'>;
  classNames: string | string[];
};
```

and we would include the `variant` in the classNames..? I see the problem with the lax typing but idk what would be best without changing tooo much again

**Comment by sebald** [comment]
Variants are part of css. But maybe rather have it on the root?

I think is worth the effort since TS already found some wrong css props when I changed it locally 😄

**Comment by viktoria-schwarz** [comment]
What do you mean by having the variant on the root? Where is the root here :D

**Comment by sebald** [comment]
​useStyles​(​{​ element​,​ css​,​ className, variants ​}​)

**Comment by viktoria-schwarz** [comment]
> ​useStyles​(​{​ element​,​ css​,​ className, variants ​}​)
So do we decide to use this new API?

It would mean to touch every component. When should we start working on this?

**Comment by sebald** [comment]
IDK what do you think?

**Comment by viktoria-schwarz** [comment]
@ti10le do you have an opinion on this?

I think it's a topic independent of the documentation, so we can start working on it (rather sooner than later otherwise I think we'll never do it).
And concerning the exact API we just need to agree on something and stick to it :)
If what you @sebald lastly proposed works fine I would be fine with this as well.

**Comment by sebald** [comment]
Also: the person who works on this, may change the proposal if she sees fit. This is just a blueprint! 🙂

**Comment by ti10le** [comment]
Correct what you say @viktoria-schwarz: rather sooner than later
`useStyles​(​{​ element​,​ css​,​ className, variants ​}​)` --> this would be also a good API for me 👍🏼
