### ISSUE TITLE
Add Story Page for Rx Logos

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#890]
Create a page to show the Reservix logos (in gatsby docs) which are used.
It's part of the section `Design Language` in the Marigold doc. See the sections and the structure [here](https://github.com/marigold-ui/marigold/issues/743)

- [Logos and their description](https://confluence.rsvx.it/display/DESIGN/Logos)

**Comment by viktoria-schwarz** [comment]
To be honest I don't see why the logos should be part of the design system, as they are just images and not in any way themeable components.

**Comment by ti10le** [comment]
I think it's like Principles or design guidelines from UX/UI Team or something else. Informations we have to show on marigold as a story page.

**Comment by viktoria-schwarz** [comment]
But still I don't see why it should be part of Marigold as we keep it "reservix-free" so far, it is just on the confluence page for I don't see a reason why either.

**Comment by ti10le** [comment]
Ok I know what you mean. Some DS have things like this and others not. Imo it's not part of a component library but UX/UI information like this is part of a DS. Users don't want to use DS and parallel search for some infos on Confluence. What do you mean @sebald @Toshibot ?

**Comment by ti10le** [comment]
We are not at a point of state where we need something like this. Could be possible in the future but should be closed for now.
