### ISSUE TITLE
Dependabot doesn't support yarn 2

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#919]
## Description

Since we updated `yarn` to v2 `depandabot` changes only include the `package.json` not lock file. This means that the lock file will "randomly" get updated in other PRs...

## How to reproduce

See example PR from `dependabot`: https://github.com/marigold-ui/marigold/pull/899/files

## Expected behavior

Dependency updates need to update the lock file too.

## Possible solution:

This is a known problem and there seems to be no solution right now. See comment: https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-805632851

One option mentioned in the above comment is to switch to renovate bot: https://www.whitesourcesoftware.com/free-developer-tools/renovate

**Comment by viktoria-schwarz** [comment]
Renovate seems to be able to fulfill our needs, so I think it's easiest to switch to it.

**Comment by viktoria-schwarz** [comment]
The renovate bot automerges its updates into the main branch. It fires every weekend (Saturday and Sunday), by default it merges at most two updates per hour.

Dependabot is uninstalled and doesn't have any permissions anymore to push or write to the repository. Kodiak "allows" the renovate bot to merge into main.
