### ISSUE TITLE
Component - Input Group || FormGroup

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#921]
## Description

Name: InputGroup or FormGroup
Maybe we have to make a separate group for Checkbox and Radio (see react-aria links below)

Short component description
- [ ] create component
- [ ] add theme styles
- [ ] create story file
- [ ] create test file
- [ ] create index file
- [ ] create marigold docs file

Component Infos:
- [Checkbox Group](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=579%3A954), [Radio Group](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=579%3A1129)
- ~~use the [collective](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=535%3A858) option from the label (depends on #717)~~
- make it possible to give some components like Radio and Checkbox to the Group component
- add prop to display the children inline or in separate lines
- Make the FormGroup full accessible with the react-aria [useRadioGroup](https://react-spectrum.adobe.com/react-aria/useRadioGroup.html), [useCheckboxGroup](https://react-spectrum.adobe.com/react-aria/useCheckboxGroup.html).

Impressions from other DS:
- https://mui.com/components/radio-buttons/#customization
- https://react-spectrum.adobe.com/react-spectrum/RadioGroup.html

## Context

Inputs like radio or checkbox are mostly used together in a group. If we want to display such input group we need the make it easier by creating an InputGroup component.

## Consequences

We can group our input components in forms and use it in practice. Full accessible InputGroup

**Comment by ti10le** [comment]
@sebald do we need this component?
If yes than I would say its a collective Label together with <Inline>

**Comment by sebald** [comment]
I would guess so 🙂

**Comment by ti10le** [comment]
Info: Some DS have only a RadioGroup Component or usage of Radio only within a RadioGroup. It makes no sense to display a standalone radio.

**Comment by sebald** [comment]
Closed via #2008 and #2029
