### ISSUE TITLE
Document new workflow in Github and update Confluence

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#927]
Update our workflow on the respective page on Confluence concerning planning/implementation phase and working in cycles of 2/6 weeks.

### Update decision: 
We leave confluence as it is and update it with a link to the repo. 
We document our workflow in github only.

### Todos:

- [ ] update confluence page and delete our old workflows, replace it with a link to our repo
- [ ] shortly describe our new workflow in a contribute-file

**Comment by sebald** [comment]
How about adding a contribution file! :)

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by ti10le** [comment]
Both good. But I think we need Confluence documentation in the future anyway

**Comment by sebald** [comment]
I would like to have as much stuff as possible in one location. Usually
it's easier to find this way 😉

Timo Zehnle ***@***.***> schrieb am Di., 13. Apr. 2021, 08:32:

**Comment by viktoria-schwarz** [comment]
Confluence was more for Toshi in the past right? Though we can just link to GH and we document everything here :+1:

**Comment by sebald** [comment]
@viktoria-schwarz can you update the description with the decision!
