### ISSUE TITLE
Component - Action Group

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#938]
## Description

We need a action Group component to show for example buttons together in a specific way. 

Design: [Figma Action Group](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=864%3A1)

e.g.: Text Only Button together with a primary button.

## Context

Missing component we need in the future

## Consequences

We have one more component we will need for Reservix applications.

**Comment by ti10le** [comment]
Impression from [material-ui](https://material-ui.com/components/button-group/)

It would be nice to make vertical or horizontal alignment with a prop.

**Comment by sebald** [comment]
@ti10le I think this is not really a button group, but rather an "action group" (https://seek-oss.github.io/braid-design-system/components/Actions)
