### ISSUE TITLE
docs: Documentation for theme structure

### ISSUE THREAD

**Issue by viktoria-schwarz** [marigold-ui/marigold#946]
## Description

We want to document our theme structure so that it is more clear what values we demand for and why.

## Context

A global and complete documentation that explains all our design and structural decisions.

## Consequences

Our theme is well-documented.

**Comment by viktoria-schwarz** [comment]
For our new Gatsby docs site, document

1) the general theme structure:
* how it is structured (and why)
* what values need to be there for a new theme
* how we intend to use the values
* explain semantic colors

2) each theme individually:
* when to use this theme
* what makes it a unique theme

**Comment by sebald** [comment]
What about "how to use a theme?"! 😄

**Comment by viktoria-schwarz** [comment]
Well yes that would be a good start :P
Though I expect that we will have a "Get Started" where all this is explained aswell

**Comment by viktoria-schwarz** [comment]
Considering the [discussion](https://github.com/marigold-ui/marigold/discussions/998#discussion-3348533) about the details of the docs outline, this issue covers the **Theming** chapter.
