### ISSUE TITLE
Deploy Gatsby page

### ISSUE THREAD

**Issue by sebald** [marigold-ui/marigold#953]
## Description

Currently our documentation is not automatically deployed, or deployed at all. We should at least use Github pages to continuously deploy the `main` branch.

## Context

We should have a documentation for our developers and UX designers 🙈  But the documentation is kind of our product.

## Consequences

People have easy access on how to use our design system.

**Comment by viktoria-schwarz** [comment]
We deploy our documentation via gh-pages on https://marigold-ui.github.io/marigold and want to use our custom domain marigold-ui.io.

**Comment by viktoria-schwarz** [comment]
marigold-ui.io is set up as our Documentation site and is updated with each merge on the `main` branch.
